FitnessApp: NutritionPlan.cpp File Reference
NutritionPlan.cpp File Reference
#include "NutritionPlan.h"
#include <sstream>
#include <iostream>
#include "Utils.h"
Functions
FoodItem getNewFoodItem (const std::string &itemName)
Prompts the user to enter details for a new food item and returns the created FoodItem.
Function Documentation
getNewFoodItem()
FoodItem getNewFoodItem (const std::string & itemName)
Prompts the user to enter details for a new food item and returns the created FoodItem.
Parameters
itemName The name of the food item.
Returns
The created FoodItem object.
Definition at line 39 of file NutritionPlan.cpp.
{
    std::set<std::string> categories;
    int calories;
    float protein, carbohydrates, fats, portion = 0;
    while (true)
    {
        std::string category;
        std::cout << "Enter category (or 'done' to finish): ";
        std::getline(std::cin >> std::ws, category);
        if (category == "done")
        {
            break;
        }
        categories.insert(toLower(category));
    }
    getValidInput(calories, "Enter calories per 100 grams: ");
    getValidInput(protein, "Enter protein per 100 grams: ");
    getValidInput(carbohydrates, "Enter carbohydrates per 100 grams: ");
    getValidInput(fats, "Enter fats per 100 grams: ");
    getOptionalInput(portion, "Enter portion size in grams (or press enter to skip): ");
    return FoodItem{ itemName, categories, calories, protein, carbohydrates, fats, portion };
}
References getOptionalInput(), getValidInput(), readFromCSV(), and toLower().