FitnessApp: NutritionPlanViewModel.cpp File Reference
NutritionPlanViewModel.cpp File Reference
#include "NutritionPlanViewModel.h"
#include "Utils.h"
#include <iostream>
#include <sstream>
#include <set>
#include <iomanip>
#include <random>
Macros
#define NOMINMAX
Functions
void displayFoodItemsByCategory (const std::map< std::string, FoodItem > &foodItemMap, const std::string &category, std::vector< FoodItem > &filteredFoodItems)
Display food items by category.
int viewOptions ()
Display view options for the user.
bool tryLoadProfileAndGoals (const std::string &profileFilename, const std::string &goalsFilename, Profile &profile, Goals &goals)
Try loading profile and goals from CSV files.
Macro Definition Documentation
NOMINMAX
#define NOMINMAX
Definition at line 1 of file NutritionPlanViewModel.cpp.
Function Documentation
displayFoodItemsByCategory()
void displayFoodItemsByCategory (const std::map< std::string, FoodItem > & foodItemMap, const std::string & category, std::vector< FoodItem > & filteredFoodItems)
Display food items by category.
Parameters
foodItemMap The map of all food items.
category The category to filter food items by.
filteredFoodItems The vector to store the filtered food items.
Definition at line 25 of file NutritionPlanViewModel.cpp.
{
    size_t index = 1;
    std::cout << "Food items in the category '" << category << "':\n";
    for (const auto& pair : foodItemMap)
    {
        // Check if the food item belongs to the specified category
        if (pair.second.categories.find(category) != pair.second.categories.end())
        {
            // Display food item details
            std::cout << index << ". " << pair.second.name << " (Calories: " << pair.second.calories
                << " kcal, Protein: " << pair.second.protein << " g, Carbohydrates: " << pair.second.carbohydrates
                << " g, Fats: " << pair.second.fats << " g, Portion: " << pair.second.portion << " g)\n";
            filteredFoodItems.push_back(pair.second);
            index++;
        }
    }
    printWindowSizedSeparator();
}
References printWindowSizedSeparator(), and readFromCSV().
tryLoadProfileAndGoals()
bool tryLoadProfileAndGoals (const std::string & profileFilename, const std::string & goalsFilename, Profile & profile, Goals & goals)
Try loading profile and goals from CSV files.
Parameters
profileFilename The filename of the profile CSV.
goalsFilename The filename of the goals CSV.
profile The Profile object to load data into.
goals The Goals object to load data into.
Returns
True if both profile and goals are loaded successfully, otherwise false.
Definition at line 364 of file NutritionPlanViewModel.cpp.
{
    if (!profile.loadFromCSV(profileFilename) || !goals.loadFromCSV(goalsFilename))
    {
        std::cerr << "Error loading profile or goals.\n";
        return false;
    }
    return true;
}
References Goals::loadFromCSV(), Profile::loadFromCSV(), and readFromCSV().
viewOptions()
int viewOptions ()
Display view options for the user.
Returns
The number of options available.
Definition at line 211 of file NutritionPlanViewModel.cpp.
{
    std::cout << "View Options:\n";
    std::cout << "1. View All\n";
    std::cout << "2. Generate Plan by Goals\n";
    std::cout << "3. Cancel\n";
    return 3;
}