FitnessApp: ProfileView.cpp File Reference
ProfileView.cpp File Reference
#include "ProfileView.h"
#include "Utils.h"
Functions
std::string getOptionalStringInput (const std::string &prompt, const std::string &currentValue)
Prompts the user for optional string input.
int getOptionalIntInput (const std::string &prompt, int currentValue)
Prompts the user for optional integer input.
float getOptionalFloatInput (const std::string &prompt, float currentValue)
Prompts the user for optional float input.
int printFitnessGoalOptions ()
Prints the fitness goal options.
Function Documentation
getOptionalFloatInput()
float getOptionalFloatInput (const std::string & prompt, float currentValue)
Prompts the user for optional float input.
Parameters
prompt The message to display to the user.
currentValue The current value to display as default.
Returns
float The user's input or the current value if no input was given.
Definition at line 53 of file ProfileView.cpp.
{
    std::string input;
    float floatValue;
    std::cout << prompt << " (" << currentValue << "): ";
    while (true)
    {
        std::getline(std::cin, input);
        if (input.empty())
        {
            return currentValue;
        }
        if (stringToFloat(input, floatValue) && floatValue >= 0)
        {
            return floatValue;
        }
        std::cout << "Invalid input. " << prompt << " (" << currentValue << "): ";
    }
}
References readFromCSV(), and stringToFloat().
getOptionalIntInput()
int getOptionalIntInput (const std::string & prompt, int currentValue)
Prompts the user for optional integer input.
Parameters
prompt The message to display to the user.
currentValue The current value to display as default.
Returns
int The user's input or the current value if no input was given.
Definition at line 26 of file ProfileView.cpp.
{
    std::string input;
    int intValue;
    std::cout << prompt << " (" << currentValue << "): ";
    while (true)
    {
        std::getline(std::cin, input);
        if (input.empty())
        {
            return currentValue;
        }
        if (stringToInt(input, intValue) && intValue >= 0)
        {
            return intValue;
        }
        std::cout << "Invalid input. " << prompt << " (" << currentValue << "): ";
    }
}
References readFromCSV(), and stringToInt().
getOptionalStringInput()
std::string getOptionalStringInput (const std::string & prompt, const std::string & currentValue)
Prompts the user for optional string input.
Parameters
prompt The message to display to the user.
currentValue The current value to display as default.
Returns
std::string The user's input or the current value if no input was given.
Definition at line 11 of file ProfileView.cpp.
{
    std::string input;
    std::cout << prompt << " (" << currentValue << "): ";
    std::getline(std::cin, input);
    return input.empty() ? currentValue : input;
}
References readFromCSV().
printFitnessGoalOptions()
int printFitnessGoalOptions ()
Prints the fitness goal options.
Returns
int The number of options available.
Definition at line 223 of file ProfileView.cpp.
{
    std::cout << "Select fitness goal:\n";
    std::cout << "1. Weight Loss\n";
    std::cout << "2. Muscle Gain\n";
    std::cout << "3. Maintenance\n";
    return 3;
}