FitnessApp: Utils.h File Reference
Utils.h File Reference
#include <fstream>
#include <sstream>
#include <string>
#include <vector>
#include <iostream>
#include <map>
#include <functional>
#include <algorithm>
#include <unistd.h>
#include <sys/ioctl.h>
#include <cstdlib>
Typedefs
using MenuOption = std::pair<std::string, std::function<void()>>
Alias for a menu option, consisting of a display name and an action function.
Enumerations
enum class Color {
RED , GREEN , YELLOW , BLUE ,
MAGENTA , CYAN , WHITE , RESET
}
Enum for basic colors.
Functions
template<typename T >
void writeToCSV (const std::string &filename, const T &item)
Generic function to write data to a CSV file.
template<typename T >
void overwriteCSV (const std::string &filename, const std::map< std::string, T > &items)
Generic function to overwrite data in a CSV file.
template<typename T , typename U >
std::map< std::string, T > readFromCSV (const std::string &filename, const std::map< std::string, U > &itemsSource)
Generic function to read data from a CSV file into a map.
template<typename T >
std::map< std::string, T > readFromCSV (const std::string &filename)
Generic function to read data from a CSV file into a map.
template<typename T >
void getValidInput (T &variable, const std::string &prompt)
Generic helper function to get valid numeric input.
void getValidInput (int &variable, const std::string &prompt, int min, int max)
Helper function to get valid numeric input within a specified range.
template<typename T >
void getOptionalInput (T &variable, const std::string &prompt)
Template function to get optional input.
bool stringToInt (const std::string &value, int &intValue)
Function to check if a string can be converted to an integer.
bool stringToFloat (const std::string &value, float &floatValue)
Function to check if a string can be converted to a float.
void clearScreen ()
Clears the screen.
std::string getColorCode (Color color)
Function to get the color code from the Color enum.
std::string colorText (const std::string &text, Color color)
Function to color a text string with the desired color.
void printSeparator (const char symbol, Color color, size_t length)
Prints a separator line of the given length.
void printLabel (const std::string &label, Color color=Color::BLUE)
Prints a label with a separator line around it.
std::string toLower (const std::string &str)
Converts a string to lowercase.
void printWindowSizedSeparator ()
Prints a window-sized separator line for Unix-like systems.
void displayMenu (const std::string &title, const std::vector< MenuOption > &menuOptions)
Displays a menu with the given title and options.
Variables
const std::vector< std::string > DAYS_OF_WEEK = { "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday" }
vector of days of the week.
const std::vector< std::string > MEAL_NAMES = { "Breakfast", "Snack1", "Lunch", "Snack2", "Dinner" }
vector of meal names of a mealplan
Typedef Documentation
MenuOption
using MenuOption = std::pair<std::string, std::function<void()>>
Alias for a menu option, consisting of a display name and an action function.
Definition at line 282 of file Utils.h.
Enumeration Type Documentation
Color
enum class Color strong
Enum for basic colors.
Enumerator
RED
GREEN
YELLOW
BLUE
MAGENTA
CYAN
WHITE
RESET
Definition at line 301 of file Utils.h.
{
    RED,
    GREEN,
    YELLOW,
    BLUE,
    MAGENTA,
    CYAN,
    WHITE,
    RESET
};
Function Documentation
clearScreen()
void clearScreen () inline
Clears the screen.
Definition at line 287 of file Utils.h.
{
#if defined(_WIN32) || defined(_WIN64)
    // Windows system call
    system("cls");
#else
    // Unix-like system call
    std::system("clear");
#endif
}
References readFromCSV().
colorText()
std::string colorText (const std::string & text, Color color) inline
Function to color a text string with the desired color.
Parameters
text Text to color.
color Desired color.
Returns
Colored text as a string.
Definition at line 350 of file Utils.h.
{
    return getColorCode(color) + text + getColorCode(Color::RESET);
}
References getColorCode(), readFromCSV(), and RESET.
displayMenu()
void displayMenu (const std::string & title, const std::vector< MenuOption > & menuOptions) inline
Displays a menu with the given title and options.
Parameters
title Title of the menu.
menuOptions Vector of menu options.
Definition at line 434 of file Utils.h.
{
    clearScreen(); // Clear the screen before displaying the menu
    printLabel(title, Color::BLUE);
    for (size_t i = 0; i < menuOptions.size(); ++i)
    {
        std::cout << i + 1 << ". " << menuOptions[i].first << "\n";
    }
    printWindowSizedSeparator();
}
References BLUE, clearScreen(), printLabel(), printWindowSizedSeparator(), and readFromCSV().
getColorCode()
std::string getColorCode (Color color) inline
Function to get the color code from the Color enum.
Parameters
color Desired color.
Returns
Color code as a string.
Definition at line 319 of file Utils.h.
{
    switch (color)
    {
    case Color::RED:
        return "\033[1;31m";
    case Color::GREEN:
        return "\033[1;32m";
    case Color::YELLOW:
        return "\033[1;33m";
    case Color::BLUE:
        return "\033[1;34m";
    case Color::MAGENTA:
        return "\033[1;35m";
    case Color::CYAN:
        return "\033[1;36m";
    case Color::WHITE:
        return "\033[1;37m";
    case Color::RESET:
    default:
        return "\033[0m";
    }
}
References BLUE, CYAN, GREEN, MAGENTA, readFromCSV(), RED, RESET, WHITE, and YELLOW.
getOptionalInput()
template<typename T > void getOptionalInput (T & variable, const std::string & prompt)
Template function to get optional input.
Template Parameters
T Type of the variable.
Parameters
variable Variable to store the input.
prompt Prompt message for the input.
Definition at line 190 of file Utils.h.
{
    std::string input;
    while (true)
    {
        std::cout << prompt;
        std::getline(std::cin, input);
        if (input.empty())
        {
            break; // Keep current value if input is empty
        }
        std::stringstream ss(input);
        T temp;
        if (ss >> temp && ss.eof())
        { // Check if the input is valid for type T
            variable = temp;
            break;
        }
        else
        {
            std::cout << "Invalid input. ";
        }
    }
}
References readFromCSV().
getValidInput() [1/2]
void getValidInput (int & variable, const std::string & prompt, int min, int max) inline
Helper function to get valid numeric input within a specified range.
Parameters
variable Variable to store the input.
prompt Prompt message for the input.
min Minimum value for the input.
max Maximum value for the input.
Definition at line 168 of file Utils.h.
{
    std::string input;
    while (true)
    {
        getValidInput(variable, prompt);
        if (variable >= min && variable <= max)
        {
            break;
        }
        std::cout << "Invalid input. Please enter a number between " << min << " and " << max << ".\n";
    }
}
References getValidInput(), and readFromCSV().
getValidInput() [2/2]
template<typename T > void getValidInput (T & variable, const std::string & prompt)
Generic helper function to get valid numeric input.
Template Parameters
T Type of the variable.
Parameters
variable Variable to store the input.
prompt Prompt message for the input.
Definition at line 136 of file Utils.h.
{
    std::string input;
    while (true)
    {
        std::cout << prompt;
        std::getline(std::cin, input);
        std::istringstream iss(input);
        T temp;
        char extra;
        if (!(iss >> temp) || (iss >> extra))
        {
            std::cout << "Invalid input. Please enter a valid number.\n";
        }
        else
        {
            variable = temp;
            break; // Valid input
        }
    }
}
References readFromCSV().
overwriteCSV()
template<typename T > void overwriteCSV (const std::string & filename, const std::map< std::string, T > & items)
Generic function to overwrite data in a CSV file.
Template Parameters
T Type of the items to write.
Parameters
filename Name of the file.
items Map of items to overwrite the file with.
Definition at line 43 of file Utils.h.
{
    std::ofstream file(filename, std::ios::trunc); // Truncate mode to clear the file
    if (file.is_open())
    {
        for (const auto& pair : items)
        {
            writeToCSV(filename, pair.second);
        }
        file.close();
    }
    else
    {
        std::cerr << "Unable to open file for writing: " << filename << std::endl;
    }
}
References readFromCSV(), and writeToCSV().
printLabel()
void printLabel (const std::string & label, Color color = Color::BLUE) inline
Prints a label with a separator line around it.
Parameters
label Label to print.
Definition at line 372 of file Utils.h.
{
    size_t length = label.length() + 6;
    printSeparator('=', color, length);
    std::cout << colorText("|| ", color) << label << colorText(" ||", color) << std::endl;
    printSeparator('=', color, length);
}
References colorText(), printSeparator(), and readFromCSV().
printSeparator()
void printSeparator (const char symbol, Color color, size_t length) inline
Prints a separator line of the given length.
Parameters
length Length of the separator line.
Definition at line 360 of file Utils.h.
{
    std::cout << getColorCode(color); // Change the color here
    for (int i = 0; i < length; ++i) std::cout << symbol;
    std::cout << std::endl << getColorCode(Color::RESET);
}
References getColorCode(), readFromCSV(), and RESET.
printWindowSizedSeparator()
void printWindowSizedSeparator ()
Prints a window-sized separator line for Unix-like systems.
Definition at line 417 of file Utils.h.
{
    struct winsize w;
    ioctl(STDOUT_FILENO, TIOCGWINSZ, &w);
    int columns = w.ws_col;
    printSeparator('-', Color::BLUE, columns);
}
References BLUE, printSeparator(), and readFromCSV().
readFromCSV() [1/2]
template<typename T > std::map< std::string, T > readFromCSV (const std::string & filename)
Generic function to read data from a CSV file into a map.
Template Parameters
T Type of the items to read.
Parameters
filename Name of the file.
Returns
Map of items read from the file.
Definition at line 103 of file Utils.h.
{
    std::map<std::string, T> items;
    std::ifstream file(filename);
    if (file.is_open())
    {
        std::string line;
        while (std::getline(file, line))
        {
            std::stringstream ss(line);
            T item;
            if (item.fromCSV(ss))
            {
                items[item.name] = item;
            }
        }
        file.close();
    }
    else
    {
        std::cerr << "Unable to open file for reading: " << filename << std::endl;
    }
    return items;
}
References readFromCSV().
readFromCSV() [2/2]
template<typename T , typename U > std::map< std::string, T > readFromCSV (const std::string & filename, const std::map< std::string, U > & itemsSource)
Generic function to read data from a CSV file into a map.
Template Parameters
T Type of the items to read.
U Type of the items source map.
Parameters
filename Name of the file.
itemsSource Source map of items.
Returns
Map of items read from the file.
Definition at line 70 of file Utils.h.
{
    std::map<std::string, T> items;
    std::ifstream file(filename);
    if (file.is_open())
    {
        std::string line;
        while (std::getline(file, line))
        {
            std::stringstream ss(line);
            T item;
            if (item.fromCSV(ss, itemsSource))
            {
                items[item.name] = item;
            }
        }
        file.close();
    }
    else
    {
        std::cerr << "Unable to open file for reading: " << filename << std::endl;
    }
    return items;
}
References readFromCSV().
stringToFloat()
bool stringToFloat (const std::string & value, float & floatValue) inline
Function to check if a string can be converted to a float.
Parameters
value String to check.
floatValue Float value to store the result.
Returns
True if the string can be converted, false otherwise.
Definition at line 250 of file Utils.h.
{
    size_t p;
    try
    {
        floatValue = std::stof(value, &p);
        if (p != value.size())
        {
            return false;
        }
        return true;
    }
    catch (...)
    {
        return false;
    }
}
References readFromCSV().
stringToInt()
bool stringToInt (const std::string & value, int & intValue) inline
Function to check if a string can be converted to an integer.
Parameters
value String to check.
intValue Integer value to store the result.
Returns
True if the string can be converted, false otherwise.
Definition at line 223 of file Utils.h.
{
    size_t p;
    try
    {
        intValue = std::stoi(value, &p);
        if (p != value.size())
        {
            return false;
        }
        return true;
    }
    catch (...)
    {
        return false;
    }
}
References readFromCSV().
toLower()
std::string toLower (const std::string & str) inline
Converts a string to lowercase.
Parameters
str String to convert.
Returns
Lowercase version of the string.
Definition at line 386 of file Utils.h.
{
    std::string lowerStr = str;
    std::transform(lowerStr.begin(), lowerStr.end(), lowerStr.begin(), ::tolower);
    return lowerStr;
}
References readFromCSV().
writeToCSV()
template<typename T > void writeToCSV (const std::string & filename, const T & item)
Generic function to write data to a CSV file.
Template Parameters
T Type of the item to write.
Parameters
filename Name of the file.
item Item to write to the file.
Definition at line 21 of file Utils.h.
{
    std::ofstream file(filename, std::ios::app); // Append mode
    if (file.is_open())
    {
        item.toCSV(file);
        file.close();
    }
    else
    {
        std::cerr << "Unable to open file for writing: " << filename << std::endl;
    }
}
References readFromCSV().
Variable Documentation
DAYS_OF_WEEK
const std::vector<std::string> DAYS_OF_WEEK = { "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday" }
vector of days of the week.
Definition at line 272 of file Utils.h.
{ "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday" };
MEAL_NAMES
const std::vector<std::string> MEAL_NAMES = { "Breakfast", "Snack1", "Lunch", "Snack2", "Dinner" }
vector of meal names of a mealplan
Definition at line 277 of file Utils.h.
{ "Breakfast", "Snack1", "Lunch", "Snack2", "Dinner" };