FitnessApp: FoodView Class Reference
FoodView Class Reference
Handles the user interface for displaying and managing food items.
#include <FoodView.h>
Public Member Functions
FoodView (FoodViewModel &viewModel)
Constructs a FoodView object.
void display ()
Displays the food items menu and handles user interactions.
Public Member Functions inherited from View
virtual ~View ()=default
Virtual destructor for the View class.
void displayAndHandleSubMenu (const std::string &title, const std::vector< MenuOption > &menuOptions, bool askForEnterAtTheEnd)
Displays a submenu and handles user input to navigate the options.
Private Member Functions
void importFromFile ()
Imports food items from a file.
Private Attributes
FoodViewModel & viewModel
Reference to the FoodViewModel object.
std::vector< MenuOption > menuOptions
List of menu options for the food view.
Detailed Description
Handles the user interface for displaying and managing food items.
This class provides methods to display the food items menu and handle user interactions.
Definition at line 15 of file FoodView.h.
Constructor & Destructor Documentation
FoodView()
FoodView::FoodView (FoodViewModel & vm)
Constructs a FoodView object.
Parameters
viewModel A reference to the FoodViewModel object.
Initializes the menu options for food-related actions.
Parameters
vm A reference to the FoodViewModel object.
Definition at line 10 of file FoodView.cpp.
                                    : viewModel(vm)
{
    menuOptions = {
        {"View Food Items", [this]() { printLabel("Viewing Food Items"); viewModel.view(); }},
        {"Add Food Item", [this]() { printLabel("Adding a Food Item"); viewModel.add(); }},
        {"Modify Food Item", [this]() { printLabel("Modifying Food Item"); viewModel.modify(); }},
        {"Delete Food Item", [this]() { printLabel("Deleting Food Item"); viewModel.remove(); }},
        {"Import from file", [this]() { importFromFile(); }},
        {"Back", [this]() { return; }}
    };
}
References FoodViewModel::add(), importFromFile(), menuOptions, FoodViewModel::modify(), printLabel(), FoodViewModel::remove(), FoodViewModel::view(), and viewModel.
Member Function Documentation
display()
void FoodView::display () virtual
Displays the food items menu and handles user interactions.
Reloads the food items from the view model and displays the menu options.
Implements View.
Definition at line 27 of file FoodView.cpp.
{
    viewModel.reload();
    displayAndHandleSubMenu("Food", menuOptions, true);
}
References View::displayAndHandleSubMenu(), menuOptions, FoodViewModel::reload(), and viewModel.
importFromFile()
void FoodView::importFromFile () private
Imports food items from a file.
Imports food items from a specified file.
This method is used to import food items from a specified file.
Prompts the user to enter a filename and imports food items from that file.
Definition at line 38 of file FoodView.cpp.
{
    std::string filename;
    std::cout << "Enter the filename to import food items from: ";
    std::getline(std::cin >> std::ws, filename);
    viewModel.importFromFile(filename);
    std::cout << "Food items imported from file: " << filename << std::endl;
}
References FoodViewModel::importFromFile(), and viewModel.
Member Data Documentation
menuOptions
std::vector<MenuOption> FoodView::menuOptions private
List of menu options for the food view.
Definition at line 32 of file FoodView.h.
viewModel
FoodViewModel& FoodView::viewModel private
Reference to the FoodViewModel object.
Definition at line 31 of file FoodView.h.
The documentation for this class was generated from the following files:
FoodView.h
FoodView.cpp