FitnessApp: Goals Class Reference
Goals Class Reference
The Goals class represents a user's fitness goals and calculates daily caloric needs based on the profile.
#include <Goals.h>
Public Types
enum class FitnessGoal { WEIGHT_LOSS , MUSCLE_GAIN , MAINTENANCE }
Enumeration representing different fitness goals.
Public Member Functions
Goals ()
Constructs a Goals object with default values.
void setProfile (const Profile *profile)
Sets the profile to be used for caloric calculations.
void setGoals (float targetWeight, float bodyFatPercentage, FitnessGoal fitnessGoal)
Sets the fitness goals for the user.
void displayGoals () const
Displays the current goals to the console.
void setCustomCalories (float calories)
Sets custom daily caloric intake.
void resetToCalculatedCalories ()
Resets to calculated daily caloric intake based on profile and fitness goals.
float getDailyCalories () const
Gets the daily caloric needs based on either custom or calculated value.
void saveToCSV (const std::string &filename) const
Saves the goals information to a CSV file.
bool loadFromCSV (const std::string &filename)
Loads the goals information from a CSV file.
FitnessGoal getFitnessGoal () const
Gets the current fitness goal.
float getWeight () const
Gets the current weight from the profile.
float getBodyFatPercentage () const
Gets the target body fat percentage.
float getTargetWeight () const
Gets the target weight.
std::string getFitnessGoalString () const
Gets the string representation of the current fitness goal.
Private Member Functions
float calculateDailyCalories () const
Calculates the daily caloric needs based on the profile and fitness goals.
void recalculateDailyCalories ()
Recalculates daily calories if custom calories are not used.
Private Attributes
float targetWeight
The target weight in kilograms.
float bodyFatPercentage
The target body fat percentage.
FitnessGoal fitnessGoal
The fitness goal.
float customCalories
The custom daily caloric intake.
bool useCustomCalories
Flag indicating if custom calories are used.
const Profile * profile
Pointer to the Profile object.
Detailed Description
The Goals class represents a user's fitness goals and calculates daily caloric needs based on the profile.
Definition at line 12 of file Goals.h.
Member Enumeration Documentation
FitnessGoal
enum class Goals::FitnessGoal strong
Enumeration representing different fitness goals.
Enumerator
WEIGHT_LOSS
MUSCLE_GAIN
MAINTENANCE
Definition at line 18 of file Goals.h.
    {
        WEIGHT_LOSS,
        MUSCLE_GAIN,
        MAINTENANCE
    };
Constructor & Destructor Documentation
Goals()
Goals::Goals ()
Constructs a Goals object with default values.
Default constructor for the Goals class.
Definition at line 6 of file Goals.cpp.
    : targetWeight(0), bodyFatPercentage(0), fitnessGoal(FitnessGoal::MAINTENANCE), customCalories(0), useCustomCalories(false), profile(nullptr)
{
}
Member Function Documentation
calculateDailyCalories()
float Goals::calculateDailyCalories () const private
Calculates the daily caloric needs based on the profile and fitness goals.
Calculates the daily caloric needs based on profile information and fitness goals.
Returns
The calculated daily calories.
float The calculated daily calories.
Definition at line 97 of file Goals.cpp.
{
    if (profile == nullptr)
    {
        return 2000; // Default value if profile is not set
    }
    float baseCalories = profile->calculateDailyCalories();
    switch (fitnessGoal)
    {
    case FitnessGoal::WEIGHT_LOSS:
        return baseCalories - 500;
    case FitnessGoal::MUSCLE_GAIN:
        return baseCalories + 500;
    case FitnessGoal::MAINTENANCE:
    default:
        return baseCalories;
    }
}
References Profile::calculateDailyCalories(), fitnessGoal, MAINTENANCE, MUSCLE_GAIN, profile, readFromCSV(), and WEIGHT_LOSS.
displayGoals()
void Goals::displayGoals () const
Displays the current goals to the console.
Displays the goals information.
Definition at line 41 of file Goals.cpp.
{
    std::cout << "Target Weight: " << targetWeight << " kg\n";
    std::cout << "Body Fat Percentage: " << bodyFatPercentage << " %\n";
    std::cout << "Fitness Goal: ";
    switch (fitnessGoal)
    {
    case FitnessGoal::WEIGHT_LOSS:
        std::cout << "Weight Loss\n";
        break;
    case FitnessGoal::MUSCLE_GAIN:
        std::cout << "Muscle Gain\n";
        break;
    case FitnessGoal::MAINTENANCE:
        std::cout << "Maintenance\n";
        break;
    }
    std::cout << "Daily Calories: " << getDailyCalories() << "\n";
}
References bodyFatPercentage, fitnessGoal, getDailyCalories(), MAINTENANCE, MUSCLE_GAIN, targetWeight, and WEIGHT_LOSS.
getBodyFatPercentage()
float Goals::getBodyFatPercentage () const
Gets the target body fat percentage.
Gets the body fat percentage.
Returns
The target body fat percentage.
float The body fat percentage.
Definition at line 213 of file Goals.cpp.
{
    return bodyFatPercentage;
}
References bodyFatPercentage.
getDailyCalories()
float Goals::getDailyCalories () const
Gets the daily caloric needs based on either custom or calculated value.
Gets the daily calories based on either custom or calculated value.
Returns
The daily caloric intake.
float The daily calories.
Definition at line 87 of file Goals.cpp.
{
    return useCustomCalories ? customCalories : calculateDailyCalories();
}
References calculateDailyCalories(), customCalories, and useCustomCalories.
getFitnessGoal()
Goals::FitnessGoal Goals::getFitnessGoal () const
Gets the current fitness goal.
Gets the fitness goal.
Returns
The current fitness goal.
FitnessGoal The fitness goal.
Definition at line 193 of file Goals.cpp.
{
    return fitnessGoal;
}
References fitnessGoal.
getFitnessGoalString()
std::string Goals::getFitnessGoalString () const
Gets the string representation of the current fitness goal.
Converts the fitness goal to a string representation.
Returns
The string representation of the fitness goal.
std::string The string representation of the fitness goal.
Definition at line 233 of file Goals.cpp.
{
    switch (fitnessGoal)
    {
    case FitnessGoal::WEIGHT_LOSS:
        return "Weight Loss";
    case FitnessGoal::MUSCLE_GAIN:
        return "Muscle Gain";
    case FitnessGoal::MAINTENANCE:
    default:
        return "Maintenance";
    }
}
References fitnessGoal, MAINTENANCE, MUSCLE_GAIN, and WEIGHT_LOSS.
getTargetWeight()
float Goals::getTargetWeight () const
Gets the target weight.
Returns
The target weight.
float The target weight.
Definition at line 223 of file Goals.cpp.
{
    return targetWeight;
}
References targetWeight.
getWeight()
float Goals::getWeight () const
Gets the current weight from the profile.
Returns
The current weight.
float The current weight.
Definition at line 203 of file Goals.cpp.
{
    return profile != nullptr ? profile->getWeight() : 0;
}
References Profile::getWeight(), and profile.
loadFromCSV()
bool Goals::loadFromCSV (const std::string & filename)
Loads the goals information from a CSV file.
Parameters
filename The name of the file to load the goals information from.
Returns
true if the file was successfully loaded, false otherwise.
Parameters
filename The name of the file to load the goals information.
Returns
true If the file was successfully loaded.
false If the file could not be opened.
Definition at line 156 of file Goals.cpp.
{
    std::ifstream file(filename);
    if (file.is_open())
    {
        std::string line;
        if (std::getline(file, line))
        {
            std::istringstream ss(line);
            std::string token;
            std::getline(ss, token, ',');
            targetWeight = std::stof(token);
            std::getline(ss, token, ',');
            bodyFatPercentage = std::stof(token);
            std::getline(ss, token, ',');
            fitnessGoal = static_cast<FitnessGoal>(std::stoi(token));
            std::getline(ss, token, ',');
            customCalories = std::stof(token);
            std::getline(ss, token, ',');
            useCustomCalories = std::stoi(token);
        }
        file.close();
        return true;
    }
    else
    {
        std::cerr << "Unable to open file for reading: " << filename << std::endl;
        return false;
    }
}
References bodyFatPercentage, customCalories, fitnessGoal, readFromCSV(), targetWeight, and useCustomCalories.
recalculateDailyCalories()
void Goals::recalculateDailyCalories () private
Recalculates daily calories if custom calories are not used.
Definition at line 121 of file Goals.cpp.
{
    if (!useCustomCalories)
    {
        customCalories = calculateDailyCalories();
    }
}
References calculateDailyCalories(), customCalories, and useCustomCalories.
resetToCalculatedCalories()
void Goals::resetToCalculatedCalories ()
Resets to calculated daily caloric intake based on profile and fitness goals.
Resets to calculated daily calories based on profile and fitness goals.
Definition at line 76 of file Goals.cpp.
{
    useCustomCalories = false;
    saveToCSV("goals.csv");
}
References saveToCSV(), and useCustomCalories.
saveToCSV()
void Goals::saveToCSV (const std::string & filename) const
Saves the goals information to a CSV file.
Parameters
filename The name of the file to save the goals information.
Definition at line 134 of file Goals.cpp.
{
    std::ofstream file(filename);
    if (file.is_open())
    {
        file << targetWeight << ',' << bodyFatPercentage << ','
            << static_cast<int>(fitnessGoal) << ',' << customCalories << ',' << useCustomCalories << '\n';
        file.close();
    }
    else
    {
        std::cerr << "Unable to open file for writing: " << filename << std::endl;
    }
}
References bodyFatPercentage, customCalories, fitnessGoal, readFromCSV(), targetWeight, and useCustomCalories.
setCustomCalories()
void Goals::setCustomCalories (float calories)
Sets custom daily caloric intake.
Sets custom daily calories and saves it to a file.
Parameters
calories The custom daily calories.
Definition at line 66 of file Goals.cpp.
{
    customCalories = calories;
    useCustomCalories = true;
    saveToCSV("goals.csv");
}
References customCalories, saveToCSV(), and useCustomCalories.
setGoals()
void Goals::setGoals (float targetWeight, float bodyFatPercentage, FitnessGoal fitnessGoal)
Sets the fitness goals for the user.
Sets the goals for the user.
Parameters
targetWeight The target weight in kilograms.
bodyFatPercentage The target body fat percentage.
fitnessGoal The fitness goal (weight loss, muscle gain, maintenance).
targetWeight The target weight in kg.
bodyFatPercentage The target body fat percentage.
fitnessGoal The fitness goal (weight loss, muscle gain, maintenance).
Definition at line 29 of file Goals.cpp.
{
    this->targetWeight = targetWeight;
    this->bodyFatPercentage = bodyFatPercentage;
    this->fitnessGoal = fitnessGoal;
    useCustomCalories = false;
    recalculateDailyCalories();
}
References bodyFatPercentage, fitnessGoal, recalculateDailyCalories(), targetWeight, and useCustomCalories.
setProfile()
void Goals::setProfile (const Profile * profile)
Sets the profile to be used for caloric calculations.
Sets the profile used for calculating daily calories.
Parameters
profile A pointer to the Profile object.
Definition at line 16 of file Goals.cpp.
{
    this->profile = profile;
    recalculateDailyCalories();
}
References profile, and recalculateDailyCalories().
Member Data Documentation
bodyFatPercentage
float Goals::bodyFatPercentage private
The target body fat percentage.
Definition at line 122 of file Goals.h.
customCalories
float Goals::customCalories private
The custom daily caloric intake.
Definition at line 124 of file Goals.h.
fitnessGoal
FitnessGoal Goals::fitnessGoal private
The fitness goal.
Definition at line 123 of file Goals.h.
profile
const Profile* Goals::profile private
Pointer to the Profile object.
Definition at line 126 of file Goals.h.
targetWeight
float Goals::targetWeight private
The target weight in kilograms.
Definition at line 121 of file Goals.h.
useCustomCalories
bool Goals::useCustomCalories private
Flag indicating if custom calories are used.
Definition at line 125 of file Goals.h.
The documentation for this class was generated from the following files:
Goals.h
Goals.cpp