FitnessApp: ExerciseViewModel Class Reference
ExerciseViewModel Class Reference
ViewModel class for managing and displaying exercises.
#include <ExerciseViewModel.h>
Public Member Functions
ExerciseViewModel (const std::string &file)
Construct a new ExerciseViewModel object.
void view () override
Display available exercises based on user's choice (all or by muscle group).
void add () override
Add a new exercise to the exercise map.
void modify () override
Modify an existing exercise.
void remove () override
Remove an exercise from the exercise map.
void importFromFile (const std::string &filename) override
Import exercises from a CSV file.
void reload () override
Reload the exercises from the CSV file.
Public Member Functions inherited from ViewModel
template<typename T >
bool confirmOverwrite (std::map< std::string, T > &itemMap, const std::string &name)
Prompts the user to confirm overwriting an existing item.
Private Member Functions
void displayAllExercises () const
Display all exercises.
void displayMuscleGroupOptions () const
Display options for muscle groups.
void displayExercisesByMuscleGroup (const std::string &muscleGroup) const
Display exercises by muscle group.
std::string getMuscleGroupSelection () const
Get the user's choice of muscle group.
bool confirmDeletion (const std::string &name) const
Confirm if the user wants to delete an exercise.
void overwriteExercise (const std::pair< std::string, Exercise > &item)
Overwrite an existing exercise.
void handleExerciseModification (Exercise &exercise)
Handle the modification of an exercise.
void handleExerciseDeletion (std::map< std::string, Exercise > &filteredExercises)
Handle the deletion of an exercise.
void handleMuscleGroupSelection (std::map< std::string, Exercise > &filteredExercises) const
Handle the selection of a muscle group and filter exercises accordingly.
void printExercise (const Exercise &exercise) const
Print the details of a given exercise.
void printExerciseDetails (const std::string &prefix, const Exercise &exercise) const
Print the details of a given exercise with a prefix.
void printMuscleGroupSelection (const std::vector< std::string > &muscleGroups) const
Print the muscle group selection options.
Private Attributes
std::string filename
The filename to read/write exercise items.
std::map< std::string, Exercise > exerciseMap
Map of exercise names to Exercise objects.
Detailed Description
ViewModel class for managing and displaying exercises.
Definition at line 13 of file ExerciseViewModel.h.
Constructor & Destructor Documentation
ExerciseViewModel()
ExerciseViewModel::ExerciseViewModel (const std::string & file)
Construct a new ExerciseViewModel object.
Construct a new ExerciseViewModel::ExerciseViewModel object.
Parameters
file The filename to read exercise items from.
file The filename to read exercise items from
Definition at line 12 of file ExerciseViewModel.cpp.
                                                          : filename(file)
{
    exerciseMap = readFromCSV<Exercise>(filename);
}
References exerciseMap, filename, and readFromCSV().
Member Function Documentation
add()
void ExerciseViewModel::add () override virtual
Add a new exercise to the exercise map.
Implements ViewModel.
Definition at line 133 of file ExerciseViewModel.cpp.
{
    std::string name, muscleGroup;
    int repetitions, sets, typeChoice;
    Exercise::ExerciseType type;
    std::cout << "Enter exercise name: ";
    std::getline(std::cin >> std::ws, name);
    if (!confirmOverwrite(exerciseMap, name))
    {
        std::cout << "Exercise not modified.\n";
        return;
    }
    std::cout << "Select exercise type:\n";
    std::cout << "1. Strength\n";
    std::cout << "2. Hypertrophy\n";
    std::cout << "3. Endurance\n";
    std::cout << "4. Flexibility\n";
    std::cout << "5. Balance and Stability\n";
    std::cout << "6. Power\n";
    std::cout << "7. Functional\n";
    std::cout << "8. Aerobic\n";
    std::cout << "9. Anaerobic\n";
    std::cout << "10. Recovery and Regeneration\n";
    getValidInput(typeChoice, "Enter choice: ");
    type = static_cast<Exercise::ExerciseType>(typeChoice - 1);
    std::cout << "Enter muscle group: ";
    std::getline(std::cin >> std::ws, muscleGroup);
    getValidInput(repetitions, "Enter repetitions: ");
    getValidInput(sets, "Enter sets: ");
    Exercise exercise{ name, type, toLower(muscleGroup), repetitions, sets };
    exerciseMap[name] = exercise;
    writeToCSV(filename, exercise);
}
References ViewModel::confirmOverwrite(), exerciseMap, filename, getValidInput(), readFromCSV(), toLower(), and writeToCSV().
confirmDeletion()
bool ExerciseViewModel::confirmDeletion (const std::string & name) const private
Confirm if the user wants to delete an exercise.
Parameters
name The name of the exercise to delete.
Returns
true If the user confirms deletion.
false If the user does not confirm deletion.
Parameters
name The name of the exercise to delete
Returns
true If the user confirms deletion
false If the user does not confirm deletion
Definition at line 306 of file ExerciseViewModel.cpp.
{
    const auto& exercise = exerciseMap.at(name);
    std::string confirm;
    do
    {
        std::cout << "Are you sure you want to delete " << exercise.name << " (Type: " << Exercise::exerciseTypeToString(exercise.type)
            << ", Muscle Group: " << exercise.muscleGroup
            << ", Repetitions: " << exercise.repetitions << ", Sets: " << exercise.sets << ")? (yes/no): ";
        std::getline(std::cin, confirm);
    } while (confirm != "yes" && confirm != "no");
    return confirm == "yes";
}
References exerciseMap, Exercise::exerciseTypeToString(), and readFromCSV().
displayAllExercises()
void ExerciseViewModel::displayAllExercises () const private
Display all exercises.
Definition at line 20 of file ExerciseViewModel.cpp.
{
    if (exerciseMap.empty())
    {
        std::cout << "No exercises to display.\n";
        return;
    }
    std::cout << "Exercise List:\n";
    printWindowSizedSeparator();
    for (const auto& pair : exerciseMap)
    {
        printExercise(pair.second);
    }
}
References exerciseMap, printExercise(), printWindowSizedSeparator(), and readFromCSV().
displayExercisesByMuscleGroup()
void ExerciseViewModel::displayExercisesByMuscleGroup (const std::string & muscleGroup) const private
Display exercises by muscle group.
Parameters
muscleGroup The muscle group to filter by.
muscleGroup The muscle group to filter by
Definition at line 86 of file ExerciseViewModel.cpp.
{
    bool found = false;
    for (const auto& pair : exerciseMap)
    {
        if (pair.second.muscleGroup == muscleGroup)
        {
            printExercise(pair.second);
            found = true;
        }
    }
    if (!found)
    {
        std::cout << "No exercises found for muscle group: " << muscleGroup << '\n';
    }
}
References exerciseMap, printExercise(), and readFromCSV().
displayMuscleGroupOptions()
void ExerciseViewModel::displayMuscleGroupOptions () const private
Display options for muscle groups.
Definition at line 40 of file ExerciseViewModel.cpp.
{
    std::string muscleGroup = getMuscleGroupSelection();
    if (!muscleGroup.empty())
    {
        clearScreen();
        std::cout << "Exercises for " + muscleGroup + ":\n";
        displayExercisesByMuscleGroup(muscleGroup);
    }
}
References clearScreen(), displayExercisesByMuscleGroup(), and getMuscleGroupSelection().
getMuscleGroupSelection()
std::string ExerciseViewModel::getMuscleGroupSelection () const private
Get the user's choice of muscle group.
Returns
std::string The chosen muscle group.
std::string The chosen muscle group
Definition at line 56 of file ExerciseViewModel.cpp.
{
    std::vector<std::string> muscleGroups;
    for (const auto& pair : exerciseMap)
    {
        if (std::find(muscleGroups.begin(), muscleGroups.end(), pair.second.muscleGroup) == muscleGroups.end())
        {
            muscleGroups.push_back(pair.second.muscleGroup);
        }
    }
    printMuscleGroupSelection(muscleGroups);
    int muscleGroupChoice;
    getValidInput(muscleGroupChoice, "Enter the number of the muscle group: ");
    while (muscleGroupChoice < 1 || muscleGroupChoice > muscleGroups.size())
    {
        std::cout << "Invalid choice. Please enter a number between 1 and " << muscleGroups.size() << ".\n";
        getValidInput(muscleGroupChoice, "Enter the number of the muscle group: ");
    }
    return muscleGroups[muscleGroupChoice - 1];
}
References exerciseMap, getValidInput(), printMuscleGroupSelection(), and readFromCSV().
handleExerciseDeletion()
void ExerciseViewModel::handleExerciseDeletion (std::map< std::string, Exercise > & filteredExercises) private
Handle the deletion of an exercise.
Parameters
filteredExercises The map to store the filtered exercises.
filteredExercises The map to store the filtered exercises
Definition at line 384 of file ExerciseViewModel.cpp.
{
    displayAllExercises();
    int cancelIndex = static_cast<int>(filteredExercises.size()) + 1;
    std::cout << cancelIndex << ". Cancel\n";
    int choice;
    getValidInput(choice, "Enter the number of the exercise to delete: ", 1, cancelIndex);
    if (choice == cancelIndex)
    {
        std::cout << "Operation cancelled.\n";
        return;
    }
    std::vector<std::string> names;
    for (const auto& pair : filteredExercises)
    {
        names.push_back(pair.first);
    }
    if (confirmDeletion(names[choice - 1]))
    {
        exerciseMap.erase(names[choice - 1]);
        overwriteCSV(filename, exerciseMap);
        std::cout << "Exercise deleted.\n";
    }
    else
    {
        std::cout << "Exercise not deleted.\n";
    }
}
References confirmDeletion(), displayAllExercises(), exerciseMap, filename, getValidInput(), overwriteCSV(), and readFromCSV().
handleExerciseModification()
void ExerciseViewModel::handleExerciseModification (Exercise & exercise) private
Handle the modification of an exercise.
Parameters
exercise The exercise to be modified.
exercise The exercise to be modified
Definition at line 348 of file ExerciseViewModel.cpp.
{
    std::string newName, newMuscleGroup;
    int newTypeChoice;
    Exercise::ExerciseType newType = exercise.type;
    std::cout << "Enter new exercise name (or press enter to keep current): ";
    std::getline(std::cin, newName);
    if (!newName.empty())
    {
        exercise.name = newName;
    }
    std::cout << "Enter new muscle group (or press enter to keep current): ";
    std::getline(std::cin, newMuscleGroup);
    if (!newMuscleGroup.empty())
    {
        exercise.muscleGroup = newMuscleGroup;
    }
    getOptionalInput(newTypeChoice, "Enter new exercise type (or press enter to keep current): ");
    if (newTypeChoice >= 1 && newTypeChoice <= 10)
    {
        newType = static_cast<Exercise::ExerciseType>(newTypeChoice - 1);
    }
    exercise.type = newType;
    getOptionalInput(exercise.repetitions, "Enter new repetitions (or press enter to keep current): ");
    getOptionalInput(exercise.sets, "Enter new sets (or press enter to keep current): ");
}
References getOptionalInput(), and readFromCSV().
handleMuscleGroupSelection()
void ExerciseViewModel::handleMuscleGroupSelection (std::map< std::string, Exercise > & filteredExercises) const private
Handle the selection of a muscle group and filter exercises accordingly.
Parameters
filteredExercises The map to store the filtered exercises.
filteredExercises The map to store the filtered exercises
Definition at line 423 of file ExerciseViewModel.cpp.
{
    std::string muscleGroup = getMuscleGroupSelection();
    for (const auto& pair : exerciseMap)
    {
        if (pair.second.muscleGroup == muscleGroup)
        {
            filteredExercises[pair.first] = pair.second;
        }
    }
}
References exerciseMap, getMuscleGroupSelection(), and readFromCSV().
importFromFile()
void ExerciseViewModel::importFromFile (const std::string & filename) override virtual
Import exercises from a CSV file.
Parameters
filename The name of the CSV file to import exercises from.
filename The name of the CSV file to import exercises from
Implements ViewModel.
Definition at line 235 of file ExerciseViewModel.cpp.
{
    auto items = readFromCSV<Exercise>(filename);
    for (const auto& item : items)
    {
        if (exerciseMap.find(item.first) != exerciseMap.end())
        {
            overwriteExercise(item);
        }
        else
        {
            exerciseMap[item.first] = item.second;
        }
    }
    overwriteCSV(this->filename, exerciseMap);
}
References exerciseMap, filename, overwriteCSV(), overwriteExercise(), and readFromCSV().
modify()
void ExerciseViewModel::modify () override virtual
Modify an existing exercise.
Implements ViewModel.
Definition at line 176 of file ExerciseViewModel.cpp.
{
    if (exerciseMap.empty())
    {
        std::cout << "No exercises to modify.\n";
        return;
    }
    std::map<std::string, Exercise> filteredExercises;
    handleMuscleGroupSelection(filteredExercises);
    std::cout << "Choose an exercise to modify:\n";
    std::vector<std::string> names;
    for (const auto& pair : filteredExercises)
    {
        names.push_back(pair.first);
    }
    displayAllExercises();
    std::size_t cancelIndex = filteredExercises.size() + 1;
    std::cout << cancelIndex << ". Cancel\n";
    int choice;
    getValidInput(choice, "Enter the number of the exercise to modify: ", 1, static_cast<int>(cancelIndex));
    if (choice == cancelIndex)
    {
        std::cout << "Operation cancelled.\n";
        return;
    }
    handleExerciseModification(exerciseMap[names[choice - 1]]);
    overwriteCSV(filename, exerciseMap);
    std::cout << "Exercise modified.\n";
}
References displayAllExercises(), exerciseMap, filename, getValidInput(), handleExerciseModification(), handleMuscleGroupSelection(), overwriteCSV(), and readFromCSV().
overwriteExercise()
void ExerciseViewModel::overwriteExercise (const std::pair< std::string, Exercise > & item) private
Overwrite an existing exercise.
Parameters
item The pair containing the exercise name and details.
item The pair containing the exercise name and details
Definition at line 326 of file ExerciseViewModel.cpp.
{
    const auto& currentExercise = exerciseMap[item.first];
    const auto& newExercise = item.second;
    std::cout << "Exercise '" << item.first << "' already exists.\n";
    std::cout << "Current exercise:\n";
    printExercise(currentExercise);
    std::cout << "New exercise:\n";
    printExercise(newExercise);
    if (confirmOverwrite(exerciseMap, item.first))
    {
        exerciseMap[item.first] = newExercise;
    }
}
References ViewModel::confirmOverwrite(), exerciseMap, printExercise(), and readFromCSV().
printExercise()
void ExerciseViewModel::printExercise (const Exercise & exercise) const private
Print the details of a given exercise.
Parameters
exercise The exercise whose details will be printed.
exercise The exercise whose details will be printed
Definition at line 265 of file ExerciseViewModel.cpp.
{
    std::cout << "Name: " << exercise.name << ", Type: " << Exercise::exerciseTypeToString(exercise.type)
        << ", Muscle Group: " << toLower(exercise.muscleGroup)
        << ", Repetitions: " << exercise.repetitions << ", Sets: " << exercise.sets << '\n';
    printWindowSizedSeparator();
}
References Exercise::exerciseTypeToString(), printWindowSizedSeparator(), readFromCSV(), and toLower().
printExerciseDetails()
void ExerciseViewModel::printExerciseDetails (const std::string & prefix, const Exercise & exercise) const private
Print the details of a given exercise with a prefix.
Parameters
prefix The prefix string.
exercise The exercise whose details will be printed.
prefix The prefix string
exercise The exercise whose details will be printed
Definition at line 279 of file ExerciseViewModel.cpp.
{
    std::cout << prefix << exercise.name << " (Type: " << Exercise::exerciseTypeToString(exercise.type)
        << ", Muscle Group: " << exercise.muscleGroup
        << ", Repetitions: " << exercise.repetitions << ", Sets: " << exercise.sets << ")\n";
}
References Exercise::exerciseTypeToString(), and readFromCSV().
printMuscleGroupSelection()
void ExerciseViewModel::printMuscleGroupSelection (const std::vector< std::string > & muscleGroups) const private
Print the muscle group selection options.
Parameters
muscleGroups The vector of muscle groups to be displayed.
muscleGroups The vector of muscle groups to be displayed
Definition at line 291 of file ExerciseViewModel.cpp.
{
    for (size_t i = 0; i < muscleGroups.size(); ++i)
    {
        std::cout << i + 1 << ". " << muscleGroups[i] << "\n";
    }
}
References readFromCSV().
reload()
void ExerciseViewModel::reload () override virtual
Reload the exercises from the CSV file.
Implements ViewModel.
Definition at line 255 of file ExerciseViewModel.cpp.
{
    exerciseMap = readFromCSV<Exercise>(filename);
}
References exerciseMap, filename, and readFromCSV().
remove()
void ExerciseViewModel::remove () override virtual
Remove an exercise from the exercise map.
Implements ViewModel.
Definition at line 216 of file ExerciseViewModel.cpp.
{
    if (exerciseMap.empty())
    {
        std::cout << "No exercises to delete.\n";
        return;
    }
    std::map<std::string, Exercise> filteredExercises;
    handleMuscleGroupSelection(filteredExercises);
    handleExerciseDeletion(filteredExercises);
}
References exerciseMap, handleExerciseDeletion(), handleMuscleGroupSelection(), and readFromCSV().
view()
void ExerciseViewModel::view () override virtual
Display available exercises based on user's choice (all or by muscle group).
Display available exercises based on user's choice (all or by muscle group)
Implements ViewModel.
Definition at line 107 of file ExerciseViewModel.cpp.
{
    std::cout << "Do you want to view all exercises or by muscle group?\n";
    std::cout << "1. View all\n";
    std::cout << "2. View by muscle group\n";
    int choice;
    getValidInput(choice, "Enter choice: ", 1, 2);
    if (choice == 1)
    {
        displayAllExercises();
    }
    else if (choice == 2)
    {
        displayMuscleGroupOptions();
    }
    else
    {
        std::cout << "Invalid choice.\n";
    }
}
References displayAllExercises(), displayMuscleGroupOptions(), getValidInput(), and readFromCSV().
Member Data Documentation
exerciseMap
std::map<std::string, Exercise> ExerciseViewModel::exerciseMap private
Map of exercise names to Exercise objects.
Definition at line 57 of file ExerciseViewModel.h.
filename
std::string ExerciseViewModel::filename private
The filename to read/write exercise items.
Definition at line 56 of file ExerciseViewModel.h.
The documentation for this class was generated from the following files:
ExerciseViewModel.h
ExerciseViewModel.cpp