FitnessApp: MainView Class Reference
MainView Class Reference
The MainView class provides the main interface for the application.
#include <MainView.h>
Public Member Functions
MainView (ExerciseView &exerciseView, FoodView &foodView, ProfileView &profileView, WorkoutPlanView &workoutPlanView, NutritionPlanView &nutritionPlanView)
Constructs the MainView with references to the specific view components.
void display ()
Displays the main view menu.
Public Member Functions inherited from View
virtual ~View ()=default
Virtual destructor for the View class.
void displayAndHandleSubMenu (const std::string &title, const std::vector< MenuOption > &menuOptions, bool askForEnterAtTheEnd)
Displays a submenu and handles user input to navigate the options.
Private Attributes
ExerciseView & exerciseView
Reference to the ExerciseView component.
FoodView & foodView
Reference to the FoodView component.
ProfileView & profileView
Reference to the ProfileView component.
WorkoutPlanView & workoutPlanView
Reference to the WorkoutPlanView component.
NutritionPlanView & nutritionPlanView
Reference to the NutritionPlanView component.
std::vector< MenuOption > menuOptions
Vector of menu options.
Detailed Description
The MainView class provides the main interface for the application.
Definition at line 15 of file MainView.h.
Constructor & Destructor Documentation
MainView()
MainView::MainView (ExerciseView & ev, FoodView & fv, ProfileView & pv, WorkoutPlanView & wpv, NutritionPlanView & nv)
Constructs the MainView with references to the specific view components.
Parameters
exerciseView Reference to the ExerciseView component.
foodView Reference to the FoodView component.
profileView Reference to the ProfileView component.
workoutPlanView Reference to the WorkoutPlanView component.
nutritionPlanView Reference to the NutritionPlanView component.
ev Reference to the ExerciseView component.
fv Reference to the FoodView component.
pv Reference to the ProfileView component.
wpv Reference to the WorkoutPlanView component.
nv Reference to the NutritionPlanView component.
Definition at line 14 of file MainView.cpp.
    : exerciseView(ev), foodView(fv), profileView(pv), workoutPlanView(wpv), nutritionPlanView(nv)
{
    menuOptions = {
        {"Profile", [this]() { profileView.display(); }},
        {"Exercises", [this]() { exerciseView.display(); }},
        {"Food", [this]() { foodView.display(); }},
        {"Workout Plans", [this]() { workoutPlanView.display(); }},
        {"Nutrition Plans", [this]() { nutritionPlanView.display(); }},
        {"Exit", [this]() { exit(0); }}
    };
}
References ExerciseView::display(), FoodView::display(), NutritionPlanView::display(), ProfileView::display(), WorkoutPlanView::display(), exerciseView, foodView, menuOptions, nutritionPlanView, profileView, readFromCSV(), and workoutPlanView.
Member Function Documentation
display()
void MainView::display () virtual
Displays the main view menu.
Implements View.
Definition at line 30 of file MainView.cpp.
{
    displayAndHandleSubMenu("Welcome to the Fitness Database", menuOptions, false);
}
References View::displayAndHandleSubMenu(), and menuOptions.
Member Data Documentation
exerciseView
ExerciseView& MainView::exerciseView private
Reference to the ExerciseView component.
Definition at line 35 of file MainView.h.
foodView
FoodView& MainView::foodView private
Reference to the FoodView component.
Definition at line 36 of file MainView.h.
menuOptions
std::vector<MenuOption> MainView::menuOptions private
Vector of menu options.
Definition at line 40 of file MainView.h.
nutritionPlanView
NutritionPlanView& MainView::nutritionPlanView private
Reference to the NutritionPlanView component.
Definition at line 39 of file MainView.h.
profileView
ProfileView& MainView::profileView private
Reference to the ProfileView component.
Definition at line 37 of file MainView.h.
workoutPlanView
WorkoutPlanView& MainView::workoutPlanView private
Reference to the WorkoutPlanView component.
Definition at line 38 of file MainView.h.
The documentation for this class was generated from the following files:
MainView.h
MainView.cpp