FitnessApp: WorkoutPlanView Class Reference
WorkoutPlanView Class Reference
The WorkoutPlanView class represents the view for managing workout plans. It provides a user interface for viewing, adding, modifying, and deleting workout plans.
#include <WorkoutPlanView.h>
Public Member Functions
WorkoutPlanView (WorkoutPlanViewModel &vm)
Constructs a new WorkoutPlanView object.
void display ()
Displays the workout plan view menu and handles user interaction.
Public Member Functions inherited from View
virtual ~View ()=default
Virtual destructor for the View class.
void displayAndHandleSubMenu (const std::string &title, const std::vector< MenuOption > &menuOptions, bool askForEnterAtTheEnd)
Displays a submenu and handles user input to navigate the options.
Private Member Functions
void importFromFile ()
Prompts the user to enter a filename and imports workout plans from the specified file.
Private Attributes
WorkoutPlanViewModel & viewModel
Reference to the view model for workout plans.
std::vector< MenuOption > menuOptions
List of menu options for user interaction.
Detailed Description
The WorkoutPlanView class represents the view for managing workout plans. It provides a user interface for viewing, adding, modifying, and deleting workout plans.
Definition at line 11 of file WorkoutPlanView.h.
Constructor & Destructor Documentation
WorkoutPlanView()
WorkoutPlanView::WorkoutPlanView (WorkoutPlanViewModel & vm)
Constructs a new WorkoutPlanView object.
Parameters
vm The WorkoutPlanViewModel to be used by this view.
Definition at line 9 of file WorkoutPlanView.cpp.
                                                         : viewModel(vm)
{
    menuOptions = {
        {"View Workout Plans", [this]() { printLabel("Viewing Workout Plans"); viewModel.view(); }},
        {"Add Workout Plan", [this]() { printLabel("Adding Workout Plan"); viewModel.add(); }},
        {"Modify Workout Plan", [this]() { printLabel("Modifying Workout Plan"); viewModel.modify(); }},
        {"Delete Workout Plan", [this]() { printLabel("Deleting Workout Plan"); viewModel.remove(); }},
        {"Import Workout Plan from File", [this]() { importFromFile(); }},
        {"Back", [this]() { return; }}
    };
}
References WorkoutPlanViewModel::add(), importFromFile(), menuOptions, WorkoutPlanViewModel::modify(), printLabel(), WorkoutPlanViewModel::remove(), WorkoutPlanViewModel::view(), and viewModel.
Member Function Documentation
display()
void WorkoutPlanView::display () virtual
Displays the workout plan view menu and handles user interaction.
Implements View.
Definition at line 24 of file WorkoutPlanView.cpp.
{
    viewModel.reload();
    displayAndHandleSubMenu("Workout Plans", menuOptions, true);
}
References View::displayAndHandleSubMenu(), menuOptions, WorkoutPlanViewModel::reload(), and viewModel.
importFromFile()
void WorkoutPlanView::importFromFile () private
Prompts the user to enter a filename and imports workout plans from the specified file.
Definition at line 33 of file WorkoutPlanView.cpp.
{
    std::string filename;
    std::cout << "Enter the filename to import workout plans from: ";
    std::getline(std::cin >> std::ws, filename);
    viewModel.importFromFile(filename);
    std::cout << "Workout plans imported from file: " << filename << std::endl;
}
References WorkoutPlanViewModel::importFromFile(), and viewModel.
Member Data Documentation
menuOptions
std::vector<MenuOption> WorkoutPlanView::menuOptions private
List of menu options for user interaction.
Definition at line 27 of file WorkoutPlanView.h.
viewModel
WorkoutPlanViewModel& WorkoutPlanView::viewModel private
Reference to the view model for workout plans.
Definition at line 26 of file WorkoutPlanView.h.
The documentation for this class was generated from the following files:
WorkoutPlanView.h
WorkoutPlanView.cpp