FitnessApp: FoodItem Class Reference
FoodItem Class Reference
Class representing a food item with nutritional information.
#include <FoodItem.h>
Public Member Functions
FoodItem ()=default
Default constructor.
FoodItem (std::string name, std::set< std::string > categories, int calories, float protein, float carbohydrates, float fats, float portion=0)
Parameterized constructor.
void toCSV (std::ostream &os) const
Serializes the food item to a CSV stream.
bool fromCSV (std::istream &is)
Parses a food item from a CSV stream.
void displayNutritionalValues (float quantity) const
Displays the nutritional values for a given quantity of the food item.
Public Attributes
std::string name
Name of the food item.
std::set< std::string > categories
Categories the food item belongs to.
int calories = 0
Calories per 100 grams.
float protein = 0
Protein content per 100 grams.
float carbohydrates = 0
Carbohydrate content per 100 grams.
float fats = 0
Fat content per 100 grams.
float portion = 0
Portion size in grams.
Detailed Description
Class representing a food item with nutritional information.
Definition at line 13 of file FoodItem.h.
Constructor & Destructor Documentation
FoodItem() [1/2]
FoodItem::FoodItem () default
Default constructor.
FoodItem() [2/2]
FoodItem::FoodItem (std::string name, std::set< std::string > categories, int calories, float protein, float carbohydrates, float fats, float portion = 0) inline
Parameterized constructor.
Parameters
name Name of the food item.
categories Categories the food item belongs to.
calories Calories per 100 grams.
protein Protein content per 100 grams.
carbohydrates Carbohydrate content per 100 grams.
fats Fat content per 100 grams.
portion Portion size in grams (default is 0).
Definition at line 40 of file FoodItem.h.
        : name(std::move(name)), categories(std::move(categories)), calories(calories), protein(protein), carbohydrates(carbohydrates), fats(fats), portion(portion)
    {
    }
Member Function Documentation
displayNutritionalValues()
void FoodItem::displayNutritionalValues (float quantity) const
Displays the nutritional values for a given quantity of the food item.
Parameters
quantity Quantity in grams.
Definition at line 54 of file FoodItem.cpp.
{
    std::cout << "Nutritional values for " << quantity << " grams of " << name << ":\n";
    std::cout << "Calories: " << (calories * quantity / 100) << " kcal\n";
    std::cout << "Protein: " << (protein * quantity / 100) << " g\n";
    std::cout << "Carbohydrates: " << (carbohydrates * quantity / 100) << " g\n";
    std::cout << "Fats: " << (fats * quantity / 100) << " g\n";
    std::cout << "Portion size: " << portion << " grams\n";
}
References calories, carbohydrates, fats, name, portion, protein, and readFromCSV().
fromCSV()
bool FoodItem::fromCSV (std::istream & is)
Parses a food item from a CSV stream.
Parameters
is Input stream to read from.
Returns
True if parsing was successful, false otherwise.
Definition at line 24 of file FoodItem.cpp.
{
    std::string categoriesStr, calStr, proteinStr, carbStr, fatsStr, portionStr;
    if (std::getline(is, name, ',') && std::getline(is, categoriesStr, ',') &&
        std::getline(is, calStr, ',') && std::getline(is, proteinStr, ',') &&
        std::getline(is, carbStr, ',') && std::getline(is, fatsStr, ',') &&
        std::getline(is, portionStr))
    {
        std::stringstream ss(categoriesStr);
        std::string category;
        while (std::getline(ss, category, ';'))
        {
            categories.insert(category);
        }
        calories = std::stoi(calStr);
        protein = std::stof(proteinStr);
        carbohydrates = std::stof(carbStr);
        fats = std::stof(fatsStr);
        portion = std::stof(portionStr);
        return true;
    }
    return false;
}
References calories, carbohydrates, categories, fats, name, portion, protein, and readFromCSV().
toCSV()
void FoodItem::toCSV (std::ostream & os) const
Serializes the food item to a CSV stream.
Parameters
os Output stream to write to.
Definition at line 8 of file FoodItem.cpp.
{
    os << name << ",";
    for (const auto& category : categories)
    {
        os << category << ";";
    }
    os << "," << calories << "," << protein << "," << carbohydrates << "," << fats << "," << portion << "\n";
}
References calories, carbohydrates, categories, fats, name, portion, protein, and readFromCSV().
Member Data Documentation
calories
int FoodItem::calories = 0
Calories per 100 grams.
Definition at line 18 of file FoodItem.h.
carbohydrates
float FoodItem::carbohydrates = 0
Carbohydrate content per 100 grams.
Definition at line 20 of file FoodItem.h.
categories
std::set<std::string> FoodItem::categories
Categories the food item belongs to.
Definition at line 17 of file FoodItem.h.
fats
float FoodItem::fats = 0
Fat content per 100 grams.
Definition at line 21 of file FoodItem.h.
name
std::string FoodItem::name
Name of the food item.
Definition at line 16 of file FoodItem.h.
portion
float FoodItem::portion = 0
Portion size in grams.
Definition at line 22 of file FoodItem.h.
protein
float FoodItem::protein = 0
Protein content per 100 grams.
Definition at line 19 of file FoodItem.h.
The documentation for this class was generated from the following files:
FoodItem.h
FoodItem.cpp