FitnessApp: NutritionPlan Class Reference
NutritionPlan Class Reference
Represents a nutrition plan consisting of meals and their respective food items and portion sizes.
#include <NutritionPlan.h>
Public Member Functions
NutritionPlan ()=default
Default constructor for NutritionPlan.
NutritionPlan (std::string name, std::map< std::string, std::vector< std::pair< FoodItem, float > > > meals)
Parameterized constructor for NutritionPlan.
void toCSV (std::ostream &os) const
Converts the nutrition plan to CSV format and writes it to the given output stream.
bool fromCSV (std::istream &is, const std::map< std::string, FoodItem > &items)
Loads the nutrition plan from CSV format from the given input stream.
void display () const
Displays the nutrition plan details to the standard output.
void adjustPortionSizes (float factor)
Adjusts the portion sizes of all meals in the nutrition plan by a given factor.
void getNewNutritionPlan (std::istringstream &ss, const std::map< std::string, FoodItem > &items, const std::string &mealName)
Gets a new nutrition plan for a specific meal name.
Public Attributes
std::string name
The name of the nutrition plan.
std::map< std::string, std::vector< std::pair< FoodItem, float > > > meals
Meal name to list of (FoodItem, portion size).
Detailed Description
Represents a nutrition plan consisting of meals and their respective food items and portion sizes.
Definition at line 13 of file NutritionPlan.h.
Constructor & Destructor Documentation
NutritionPlan() [1/2]
NutritionPlan::NutritionPlan () default
Default constructor for NutritionPlan.
NutritionPlan() [2/2]
NutritionPlan::NutritionPlan (std::string name, std::map< std::string, std::vector< std::pair< FoodItem, float > > > meals) inline
Parameterized constructor for NutritionPlan.
Parameters
name The name of the nutrition plan.
meals A map of meal names to their respective food items and portion sizes.
Definition at line 29 of file NutritionPlan.h.
        : name(std::move(name)), meals(std::move(meals))
    {
    }
Member Function Documentation
adjustPortionSizes()
void NutritionPlan::adjustPortionSizes (float factor)
Adjusts the portion sizes of all meals in the nutrition plan by a given factor.
Parameters
factor The factor by which to adjust the portion sizes.
Definition at line 154 of file NutritionPlan.cpp.
{
    for (auto& meal : meals)
    {
        for (auto& pair : meal.second)
        {
            pair.second *= factor;
        }
    }
}
References meals, and readFromCSV().
display()
void NutritionPlan::display () const
Displays the nutrition plan details to the standard output.
Definition at line 137 of file NutritionPlan.cpp.
{
    std::cout << "Nutrition Plan: " << name << "\n";
    for (const auto& meal : meals)
    {
        std::cout << meal.first << ":\n";
        for (const auto& pair : meal.second)
        {
            std::cout << "  " << pair.first.name << " - " << pair.second << " grams\n";
        }
    }
}
References meals, name, and readFromCSV().
fromCSV()
bool NutritionPlan::fromCSV (std::istream & is, const std::map< std::string, FoodItem > & items)
Loads the nutrition plan from CSV format from the given input stream.
Loads the nutrition plan from a CSV format from the given input stream.
Parameters
is The input stream to read the CSV data from.
items A map of available food items to look up by name.
Returns
True if the nutrition plan was successfully loaded, false otherwise.
Definition at line 116 of file NutritionPlan.cpp.
{
    std::string line;
    if (std::getline(is, line))
    {
        std::istringstream ss(line);
        if (std::getline(ss, name, ','))
        {
            for (const auto& mealName : MEAL_NAMES)
            {
                getNewNutritionPlan(ss, items, mealName);
            }
            return true;
        }
    }
    return false;
}
References getNewNutritionPlan(), MEAL_NAMES, name, and readFromCSV().
getNewNutritionPlan()
void NutritionPlan::getNewNutritionPlan (std::istringstream & ss, const std::map< std::string, FoodItem > & items, const std::string & mealName)
Gets a new nutrition plan for a specific meal name.
Reads a new nutrition plan from a CSV string stream.
Parameters
ss The input string stream containing the CSV data.
items A map of available food items to look up by name.
mealName The name of the meal to get the nutrition plan for.
ss The stringstream to read the CSV data from.
items A map of available food items to look up by name.
mealName The name of the meal to read.
Definition at line 72 of file NutritionPlan.cpp.
{
    std::string token;
    if (std::getline(ss, token, ','))
    {
        std::vector<std::pair<FoodItem, float>> mealItems;
        std::stringstream mealStream(token);
        std::string itemToken;
        while (std::getline(mealStream, itemToken, ';'))
        {
            std::istringstream itemStream(itemToken);
            std::string itemName, portionStr;
            if (std::getline(itemStream, itemName, '=') && std::getline(itemStream, portionStr))
            {
                float portion = std::stof(portionStr);
                auto it = items.find(itemName);
                if (it != items.end())
                {
                    mealItems.emplace_back(it->second, portion);
                }
                else
                {
                    std::cerr << "Food item " << itemName << " not found in the provided items map.\n";
                    FoodItem foodItem = getNewFoodItem(itemName);
                    getValidInput(portion, "Enter portion size for this meal in grams: ");
                    mealItems.emplace_back(foodItem, portion);
                    writeToCSV("food_items.csv", foodItem);
                }
            }
        }
        meals[mealName] = mealItems;
    }
}
References getNewFoodItem(), getValidInput(), meals, readFromCSV(), and writeToCSV().
toCSV()
void NutritionPlan::toCSV (std::ostream & os) const
Converts the nutrition plan to CSV format and writes it to the given output stream.
Converts the nutrition plan to a CSV format and writes it to the given output stream.
Parameters
os The output stream to write the CSV data to.
Definition at line 10 of file NutritionPlan.cpp.
{
    os << name << ",";
    for (const auto& mealName : MEAL_NAMES)
    {
        auto it = meals.find(mealName);
        if (it != meals.end())
        {
            for (size_t i = 0; i < it->second.size(); ++i)
            {
                const auto& foodPair = it->second[i];
                os << foodPair.first.name << "=" << foodPair.second;
                if (i < it->second.size() - 1)
                {
                    os << ";";
                }
            }
        }
        os << ",";
    }
    os << "\n";
}
References MEAL_NAMES, meals, name, and readFromCSV().
Member Data Documentation
meals
std::map<std::string, std::vector<std::pair<FoodItem, float> > > NutritionPlan::meals
Meal name to list of (FoodItem, portion size).
Definition at line 17 of file NutritionPlan.h.
name
std::string NutritionPlan::name
The name of the nutrition plan.
Definition at line 16 of file NutritionPlan.h.
The documentation for this class was generated from the following files:
NutritionPlan.h
NutritionPlan.cpp