FitnessApp: View Class Reference
View Class Reference abstract
Abstract base class for all views in the application.
#include <View.h>
Public Member Functions
virtual ~View ()=default
Virtual destructor for the View class.
virtual void display ()=0
Pure virtual function to display the view.
void displayAndHandleSubMenu (const std::string &title, const std::vector< MenuOption > &menuOptions, bool askForEnterAtTheEnd)
Displays a submenu and handles user input to navigate the options.
Detailed Description
Abstract base class for all views in the application.
Definition at line 12 of file View.h.
Constructor & Destructor Documentation
~View()
virtual View::~View () virtual default
Virtual destructor for the View class.
Member Function Documentation
display()
virtual void View::display () pure virtual
Pure virtual function to display the view.
Implemented in ExerciseView, FoodView, MainView, NutritionPlanView, ProfileView, and WorkoutPlanView.
displayAndHandleSubMenu()
void View::displayAndHandleSubMenu (const std::string & title, const std::vector< MenuOption > & menuOptions, bool askForEnterAtTheEnd) inline
Displays a submenu and handles user input to navigate the options.
Parameters
title The title of the submenu.
menuOptions A vector of menu options to display.
askForEnterAtTheEnd A boolean indicating whether to ask for Enter key press at the end.
Definition at line 32 of file View.h.
    {
        std::string input;
        int choice;
        while (true)
        {
            clearScreen(); // Clear the screen before displaying the menu
            displayMenu(title, menuOptions);
            std::cout << "Select an action: ";
            std::getline(std::cin >> std::ws, input);
            try
            {
                size_t pos;
                choice = std::stoi(input, &pos);
                // If pos is not at the end of the string, then not all characters were valid numbers
                if (pos != input.length())
                {
                    choice = 0; // Invalid choice
                }
            }
            catch (const std::exception&)
            {
                choice = 0; // Invalid choice
            }
            if (choice < 1 || choice > static_cast<int>(menuOptions.size()))
            {
                std::cout << "Invalid input, please enter a number between 1 and " << menuOptions.size() << ".\n";
                std::cout << "Press Enter to continue...";
                std::cin.get();
                clearScreen(); // Clear the screen for the next iteration
                continue;
            }
            clearScreen();
            if (choice == static_cast<int>(menuOptions.size()))
            {
                return; // Exit the loop and return to the previous menu
            }
            menuOptions[choice - 1].second();
            if (askForEnterAtTheEnd)
            {
                // After performing the action, display a message and show options again
                std::cout << "Press Enter to continue...";
                std::cin.get(); // Actually get the Enter key
                clearScreen(); // Clear the screen for the next iteration
            }
        }
    }
References clearScreen(), displayMenu(), and readFromCSV().
The documentation for this class was generated from the following file:
View.h