FitnessApp: Profile Class Reference
Profile Class Reference
The Profile class represents a user's profile with personal information and activity level.
#include <Profile.h>
Public Types
enum class Gender { MALE , FEMALE }
Enumeration for gender.
enum class ActivityLevel {
SEDENTARY , LIGHTLY_ACTIVE , MODERATELY_ACTIVE , VERY_ACTIVE ,
EXTRA_ACTIVE
}
Enumeration for activity level.
Public Member Functions
Profile ()
Constructs a new Profile object with default values.
void setProfileInformation (const std::string &name, int age, Gender gender, float height, float weight, ActivityLevel activityLevel)
Sets the profile information with provided values.
void displayProfileInformation () const
Displays the profile information to the console.
float calculateDailyCalories () const
Calculates the daily caloric needs based on the profile information.
void saveToCSV (const std::string &filename) const
Saves the profile information to a CSV file.
bool loadFromCSV (const std::string &filename)
Loads the profile information from a CSV file.
float getWeight () const
Gets the weight of the user.
std::string getName () const
Gets the name of the user.
int getAge () const
Gets the age of the user.
Gender getGender () const
Gets the gender of the user.
float getHeight () const
Gets the height of the user.
ActivityLevel getActivityLevel () const
Gets the activity level of the user.
std::string getGenderString () const
Converts the gender to a string representation.
std::string getActivityLevelString () const
Converts the activity level to a string representation.
Private Attributes
std::string name
The name of the user.
int age
The age of the user.
Gender gender
The gender of the user.
float height
The height of the user in cm.
float weight
The weight of the user in kg.
ActivityLevel activityLevel
The activity level of the user.
Detailed Description
The Profile class represents a user's profile with personal information and activity level.
Definition at line 12 of file Profile.h.
Member Enumeration Documentation
ActivityLevel
enum class Profile::ActivityLevel strong
Enumeration for activity level.
Enumerator
SEDENTARY
LIGHTLY_ACTIVE
MODERATELY_ACTIVE
VERY_ACTIVE
EXTRA_ACTIVE
Definition at line 27 of file Profile.h.
    {
        SEDENTARY,
        LIGHTLY_ACTIVE,
        MODERATELY_ACTIVE,
        VERY_ACTIVE,
        EXTRA_ACTIVE
    };
Gender
enum class Profile::Gender strong
Enumeration for gender.
Enumerator
MALE
FEMALE
Definition at line 18 of file Profile.h.
    {
        MALE,
        FEMALE
    };
Constructor & Destructor Documentation
Profile()
Profile::Profile ()
Constructs a new Profile object with default values.
Definition at line 6 of file Profile.cpp.
    : name(""), age(0), gender(Gender::MALE), height(0), weight(0), activityLevel(ActivityLevel::SEDENTARY)
{
}
Member Function Documentation
calculateDailyCalories()
float Profile::calculateDailyCalories () const
Calculates the daily caloric needs based on the profile information.
Returns
float The daily caloric needs.
Definition at line 67 of file Profile.cpp.
{
    float bmr;
    if (gender == Gender::MALE)
    {
        bmr = 10 * weight + 6.25f * height - 5 * age + 5;
    }
    else
    {
        bmr = 10 * weight + 6.25f * height - 5 * age - 161;
    }
    float activityFactor{};
    switch (activityLevel)
    {
    case ActivityLevel::SEDENTARY:
        activityFactor = 1.2f;
        break;
    case ActivityLevel::LIGHTLY_ACTIVE:
        activityFactor = 1.375f;
        break;
    case ActivityLevel::MODERATELY_ACTIVE:
        activityFactor = 1.55f;
        break;
    case ActivityLevel::VERY_ACTIVE:
        activityFactor = 1.725f;
        break;
    case ActivityLevel::EXTRA_ACTIVE:
        activityFactor = 1.9f;
        break;
    }
    return bmr * activityFactor;
}
References activityLevel, age, EXTRA_ACTIVE, gender, height, LIGHTLY_ACTIVE, MALE, MODERATELY_ACTIVE, readFromCSV(), SEDENTARY, VERY_ACTIVE, and weight.
displayProfileInformation()
void Profile::displayProfileInformation () const
Displays the profile information to the console.
Definition at line 34 of file Profile.cpp.
{
    std::cout << "Name: " << name << "\n";
    std::cout << "Age: " << age << "\n";
    std::cout << "Gender: " << (gender == Gender::MALE ? "Male" : "Female") << "\n";
    std::cout << "Height: " << height << " cm\n";
    std::cout << "Weight: " << weight << " kg\n";
    std::cout << "Activity Level: ";
    switch (activityLevel)
    {
    case ActivityLevel::SEDENTARY:
        std::cout << "Sedentary\n";
        break;
    case ActivityLevel::LIGHTLY_ACTIVE:
        std::cout << "Lightly Active\n";
        break;
    case ActivityLevel::MODERATELY_ACTIVE:
        std::cout << "Moderately Active\n";
        break;
    case ActivityLevel::VERY_ACTIVE:
        std::cout << "Very Active\n";
        break;
    case ActivityLevel::EXTRA_ACTIVE:
        std::cout << "Extra Active\n";
        break;
    }
}
References activityLevel, age, EXTRA_ACTIVE, gender, height, LIGHTLY_ACTIVE, MALE, MODERATELY_ACTIVE, name, SEDENTARY, VERY_ACTIVE, and weight.
getActivityLevel()
Profile::ActivityLevel Profile::getActivityLevel () const
Gets the activity level of the user.
Returns
ActivityLevel The activity level of the user.
Profile::ActivityLevel The activity level of the user.
Definition at line 218 of file Profile.cpp.
{
    return activityLevel;
}
References activityLevel.
getActivityLevelString()
std::string Profile::getActivityLevelString () const
Converts the activity level to a string representation.
Returns
std::string The string representation of the activity level.
Definition at line 246 of file Profile.cpp.
{
    switch (activityLevel)
    {
    case ActivityLevel::SEDENTARY:
        return "Sedentary";
    case ActivityLevel::LIGHTLY_ACTIVE:
        return "Lightly Active";
    case ActivityLevel::MODERATELY_ACTIVE:
        return "Moderately Active";
    case ActivityLevel::VERY_ACTIVE:
        return "Very Active";
    case ActivityLevel::EXTRA_ACTIVE:
        return "Extra Active";
    default:
        return "Unknown";
    }
}
References activityLevel, EXTRA_ACTIVE, LIGHTLY_ACTIVE, MODERATELY_ACTIVE, SEDENTARY, and VERY_ACTIVE.
getAge()
int Profile::getAge () const
Gets the age of the user.
Returns
int The age of the user.
Definition at line 178 of file Profile.cpp.
{
    return age;
}
References age.
getGender()
Profile::Gender Profile::getGender () const
Gets the gender of the user.
Returns
Gender The gender of the user.
Profile::Gender The gender of the user.
Definition at line 198 of file Profile.cpp.
{
    return gender;
}
References gender.
getGenderString()
std::string Profile::getGenderString () const
Converts the gender to a string representation.
Returns
std::string The string representation of the gender.
Definition at line 228 of file Profile.cpp.
{
    switch (gender)
    {
    case Gender::MALE:
        return "Male";
    case Gender::FEMALE:
        return "Female";
    default:
        return "Unknown";
    }
}
References FEMALE, gender, and MALE.
getHeight()
float Profile::getHeight () const
Gets the height of the user.
Returns
float The height of the user in cm.
Definition at line 208 of file Profile.cpp.
{
    return height;
}
References height.
getName()
std::string Profile::getName () const
Gets the name of the user.
Returns
std::string The name of the user.
Definition at line 188 of file Profile.cpp.
{
    return name;
}
References name.
getWeight()
float Profile::getWeight () const
Gets the weight of the user.
Returns
float The weight of the user.
Definition at line 168 of file Profile.cpp.
{
    return weight;
}
References weight.
loadFromCSV()
bool Profile::loadFromCSV (const std::string & filename)
Loads the profile information from a CSV file.
Parameters
filename The name of the file to load the profile information.
Returns
true If the file was successfully loaded.
false If the file could not be opened.
Definition at line 130 of file Profile.cpp.
{
    std::ifstream file(filename);
    if (file.is_open())
    {
        std::string line;
        if (std::getline(file, line))
        {
            std::istringstream ss(line);
            std::string token;
            std::getline(ss, name, ',');
            std::getline(ss, token, ',');
            age = std::stoi(token);
            std::getline(ss, token, ',');
            gender = (token == "Male" ? Gender::MALE : Gender::FEMALE);
            std::getline(ss, token, ',');
            height = std::stof(token);
            std::getline(ss, token, ',');
            weight = std::stof(token);
            std::getline(ss, token, ',');
            activityLevel = static_cast<ActivityLevel>(std::stoi(token));
        }
        file.close();
        return true;
    }
    else
    {
        std::cerr << "Unable to open file for reading: " << filename << std::endl;
        return false;
    }
}
References activityLevel, age, FEMALE, gender, height, MALE, name, readFromCSV(), and weight.
saveToCSV()
void Profile::saveToCSV (const std::string & filename) const
Saves the profile information to a CSV file.
Parameters
filename The name of the file to save the profile information.
Definition at line 107 of file Profile.cpp.
{
    std::ofstream file(filename);
    if (file.is_open())
    {
        file << name << ',' << age << ',' << (gender == Gender::MALE ? "Male" : "Female") << ','
            << height << ',' << weight << ','
            << static_cast<int>(activityLevel) << '\n';
        file.close();
    }
    else
    {
        std::cerr << "Unable to open file for writing: " << filename << std::endl;
    }
}
References activityLevel, age, gender, height, MALE, name, readFromCSV(), and weight.
setProfileInformation()
void Profile::setProfileInformation (const std::string & name, int age, Gender gender, float height, float weight, ActivityLevel activityLevel)
Sets the profile information with provided values.
Parameters
name The name of the user.
age The age of the user.
gender The gender of the user.
height The height of the user in cm.
weight The weight of the user in kg.
activityLevel The activity level of the user.
Definition at line 21 of file Profile.cpp.
{
    this->name = name;
    this->age = age;
    this->gender = gender;
    this->height = height;
    this->weight = weight;
    this->activityLevel = activityLevel;
}
References activityLevel, age, gender, height, name, and weight.
Member Data Documentation
activityLevel
ActivityLevel Profile::activityLevel private
The activity level of the user.
Definition at line 143 of file Profile.h.
age
int Profile::age private
The age of the user.
Definition at line 139 of file Profile.h.
gender
Gender Profile::gender private
The gender of the user.
Definition at line 140 of file Profile.h.
height
float Profile::height private
The height of the user in cm.
Definition at line 141 of file Profile.h.
name
std::string Profile::name private
The name of the user.
Definition at line 138 of file Profile.h.
weight
float Profile::weight private
The weight of the user in kg.
Definition at line 142 of file Profile.h.
The documentation for this class was generated from the following files:
Profile.h
Profile.cpp