FitnessApp: NutritionPlanView Class Reference
NutritionPlanView Class Reference
Class representing the view for managing nutrition plans.
#include <NutritionPlanView.h>
Public Member Functions
NutritionPlanView (NutritionPlanViewModel &vm)
Constructs a NutritionPlanView with the given ViewModel.
void display ()
Displays the Nutrition Plan menu and handles user interaction.
Public Member Functions inherited from View
virtual ~View ()=default
Virtual destructor for the View class.
void displayAndHandleSubMenu (const std::string &title, const std::vector< MenuOption > &menuOptions, bool askForEnterAtTheEnd)
Displays a submenu and handles user input to navigate the options.
Private Member Functions
void importFromFile ()
Prompts the user for a filename and imports nutrition plans from the specified file.
Private Attributes
NutritionPlanViewModel & viewModel
The ViewModel used by this view.
std::vector< MenuOption > menuOptions
Menu options for the Nutrition Plan view.
Detailed Description
Class representing the view for managing nutrition plans.
Definition at line 10 of file NutritionPlanView.h.
Constructor & Destructor Documentation
NutritionPlanView()
NutritionPlanView::NutritionPlanView (NutritionPlanViewModel & vm)
Constructs a NutritionPlanView with the given ViewModel.
Parameters
vm The ViewModel to be used by this view.
Definition at line 9 of file NutritionPlanView.cpp.
                                                               : viewModel(vm)
{
    menuOptions = {
        {"View Nutrition Plans", [this]() { printLabel("Viewing Nutrition Plans"); viewModel.view(); }},
        {"Add Nutrition Plan", [this]() { printLabel("Adding Nutrition Plan"); viewModel.add(); }},
        {"Modify Nutrition Plan", [this]() { printLabel("Modifying Nutrition Plan"); viewModel.modify(); }},
        {"Delete Nutrition Plan", [this]() { printLabel("Deleting Nutrition Plan"); viewModel.remove(); }},
        {"Import from file", [this]() { importFromFile(); }},
        {"Back", [this]() { return; }}
    };
}
References NutritionPlanViewModel::add(), importFromFile(), menuOptions, NutritionPlanViewModel::modify(), printLabel(), NutritionPlanViewModel::remove(), NutritionPlanViewModel::view(), and viewModel.
Member Function Documentation
display()
void NutritionPlanView::display () virtual
Displays the Nutrition Plan menu and handles user interaction.
Implements View.
Definition at line 24 of file NutritionPlanView.cpp.
{
    viewModel.reload();
    displayAndHandleSubMenu("Nutrition Plans", menuOptions, true);
}
References View::displayAndHandleSubMenu(), menuOptions, NutritionPlanViewModel::reload(), and viewModel.
importFromFile()
void NutritionPlanView::importFromFile () private
Prompts the user for a filename and imports nutrition plans from the specified file.
Definition at line 33 of file NutritionPlanView.cpp.
{
    std::string filename;
    std::cout << "Enter the filename to import nutrition plans from: ";
    std::getline(std::cin >> std::ws, filename);
    viewModel.importFromFile(filename);
    std::cout << "Nutrition plans imported from file: " << filename << std::endl;
}
References NutritionPlanViewModel::importFromFile(), and viewModel.
Member Data Documentation
menuOptions
std::vector<MenuOption> NutritionPlanView::menuOptions private
Menu options for the Nutrition Plan view.
Definition at line 27 of file NutritionPlanView.h.
viewModel
NutritionPlanViewModel& NutritionPlanView::viewModel private
The ViewModel used by this view.
Definition at line 26 of file NutritionPlanView.h.
The documentation for this class was generated from the following files:
NutritionPlanView.h
NutritionPlanView.cpp