FitnessApp: WorkoutPlanViewModel Class Reference
WorkoutPlanViewModel Class Reference
#include <WorkoutPlanViewModel.h>
Public Member Functions
WorkoutPlanViewModel (const std::string &file)
Construct a new WorkoutPlanViewModel object.
void view () override
Display the available workout plans.
void add () override
Add a new workout plan.
void modify () override
Modify an existing workout plan.
void remove () override
Remove an existing workout plan.
void importFromFile (const std::string &filename) override
Import workout plans from a CSV file.
void reload () override
Reload workout plans and exercises from CSV files.
Public Member Functions inherited from ViewModel
template<typename T >
bool confirmOverwrite (std::map< std::string, T > &itemMap, const std::string &name)
Prompts the user to confirm overwriting an existing item.
Private Member Functions
void displayAllWorkoutPlans () const
Display all workout plans.
void displayWorkoutPlansByType () const
Display workout plans filtered by type.
void displayWorkoutPlan (const WorkoutPlan &plan) const
Display the details of a specific workout plan.
void editDailyExercises (const std::string &day, std::vector< WorkoutPlan::ExerciseDetails > &exercises, std::map< std::string, Exercise > &exerciseMap)
Edit exercises for a specific day in the workout plan.
void displayCurrentExercisesForDay (const std::string &day, const std::vector< WorkoutPlan::ExerciseDetails > &exercises) const
Display the current exercises for a specific day.
void displayExercisesByMuscleGroup (const std::map< std::string, Exercise > &exerciseMap, const std::string &muscleGroup, std::vector< Exercise > &filteredExercises)
Display exercises filtered by muscle group.
void addExerciseToDay (const std::string &day, std::vector< WorkoutPlan::ExerciseDetails > &exercises, std::map< std::string, Exercise > &exerciseMap)
Add an exercise to a specific day in the workout plan.
void displayMuscleGroupOptions (std::map< std::string, Exercise > &exerciseMap, const std::string &day, std::vector< WorkoutPlan::ExerciseDetails > &exercises)
Display options for selecting a muscle group.
void handleMuscleGroupChoice (int choice, const std::vector< std::string > &muscleGroupsVec, const std::string &day, std::vector< WorkoutPlan::ExerciseDetails > &exercises, std::map< std::string, Exercise > &exerciseMap)
Handle the choice of muscle group selection.
void addCustomExercise (const std::string &day, std::vector< WorkoutPlan::ExerciseDetails > &exercises, std::map< std::string, Exercise > &exerciseMap)
Add a custom exercise to the list of exercises for a specific day.
void addExistingExerciseToDay (const std::string &muscleGroup, std::vector< WorkoutPlan::ExerciseDetails > &exercises, std::map< std::string, Exercise > &exerciseMap)
Add an existing exercise to the list of exercises for a specific day.
void deleteExerciseFromDay (std::vector< WorkoutPlan::ExerciseDetails > &exercises)
Delete an exercise from the list of exercises for a specific day.
void displayWorkoutPlanTypes () const
Display the available workout plan types.
int displayExerciseTypes () const
Display the available exercise types.
void modifyWorkoutPlan (WorkoutPlan &plan)
Modify the details of a workout plan.
void overwriteWorkoutPlan (const std::pair< std::string, WorkoutPlan > &item)
Overwrite an existing workout plan with a new one.
void addExerciseToList (const std::string &exerciseName, std::map< std::string, Exercise > &exerciseMap)
Add a new exercise to the exercise list.
Private Attributes
std::string filename
The filename to read/write workout plans.
std::map< std::string, WorkoutPlan > workoutPlanMap
The map of workout plans.
std::map< std::string, Exercise > exerciseMap
The map of exercises.
Detailed Description
Definition at line 11 of file WorkoutPlanViewModel.h.
Constructor & Destructor Documentation
WorkoutPlanViewModel()
WorkoutPlanViewModel::WorkoutPlanViewModel (const std::string & file)
Construct a new WorkoutPlanViewModel object.
Construct a new Workout Plan ViewModel object.
Parameters
file The filename to read workout plans from
Definition at line 12 of file WorkoutPlanViewModel.cpp.
                                                                : filename(file)
{
    reload();
}
References reload().
Member Function Documentation
add()
void WorkoutPlanViewModel::add () override virtual
Add a new workout plan.
Implements ViewModel.
Definition at line 430 of file WorkoutPlanViewModel.cpp.
{
    std::string name;
    std::map<std::string, std::vector<WorkoutPlan::ExerciseDetails>> weeklyPlan;
    std::map<std::string, Exercise> exerciseMap = readFromCSV<Exercise>("exercises.csv");
    std::cout << "Enter workout plan name: ";
    std::getline(std::cin >> std::ws, name);
    if (!confirmOverwrite(workoutPlanMap, name))
    {
        std::cout << "Workout plan not modified.\n";
        return;
    }
    int typeChoice;
    std::cout << "\nSelect workout plan type:\n";
    displayWorkoutPlanTypes();
    getValidInput(typeChoice, "Enter choice: ", 1, 6);
    WorkoutPlan::PlanType type = static_cast<WorkoutPlan::PlanType>(typeChoice - 1);
    for (const auto& day : DAYS_OF_WEEK)
    {
        std::vector<WorkoutPlan::ExerciseDetails> exercises;
        editDailyExercises(day, exercises, exerciseMap);
        weeklyPlan[day] = exercises;
    }
    WorkoutPlan plan(name, type, weeklyPlan);
    workoutPlanMap[name] = plan;
    overwriteCSV(filename, workoutPlanMap);
}
References ViewModel::confirmOverwrite(), DAYS_OF_WEEK, displayWorkoutPlanTypes(), editDailyExercises(), exerciseMap, filename, getValidInput(), overwriteCSV(), readFromCSV(), and workoutPlanMap.
addCustomExercise()
void WorkoutPlanViewModel::addCustomExercise (const std::string & day, std::vector< WorkoutPlan::ExerciseDetails > & exercises, std::map< std::string, Exercise > & exerciseMap) private
Add a custom exercise to the list of exercises for a specific day.
Add a custom exercise to the list of exercises.
Parameters
day The day of the week
exercises The list of exercises for the day
exerciseMap The map of all available exercises
day The day to add the custom exercise to
exercises The list of exercises for the day
exerciseMap The map of all available exercises
Definition at line 275 of file WorkoutPlanViewModel.cpp.
{
    Exercise newExercise;
    std::cout << "Enter exercise name: ";
    std::getline(std::cin >> std::ws, newExercise.name);
    std::string muscleGroup;
    std::cout << "Enter muscle group: ";
    std::getline(std::cin >> std::ws, muscleGroup);
    newExercise.muscleGroup = toLower(muscleGroup);
    int typeChoice;
    std::cout << "Select exercise type:\n";
    int count = displayExerciseTypes();
    getValidInput(typeChoice, "Enter choice: ", 1, count);
    newExercise.type = static_cast<Exercise::ExerciseType>(typeChoice - 1);
    getValidInput(newExercise.repetitions, "Enter repetitions: ");
    getValidInput(newExercise.sets, "Enter sets: ");
    exerciseMap[newExercise.name] = newExercise;
    writeToCSV("exercises.csv", newExercise);
    WorkoutPlan::ExerciseDetails ed;
    ed.exerciseName = newExercise.name;
    ed.reps = newExercise.repetitions;
    ed.sets = newExercise.sets;
    exercises.push_back(ed);
}
References displayExerciseTypes(), exerciseMap, WorkoutPlan::ExerciseDetails::exerciseName, getValidInput(), readFromCSV(), toLower(), and writeToCSV().
addExerciseToDay()
void WorkoutPlanViewModel::addExerciseToDay (const std::string & day, std::vector< WorkoutPlan::ExerciseDetails > & exercises, std::map< std::string, Exercise > & exerciseMap) private
Add an exercise to a specific day in the workout plan.
Add an exercise to the day.
Parameters
day The day of the week
exercises The list of exercises for the day
exerciseMap The map of all available exercises
day The day to add an exercise to
exercises The list of exercises for the day
exerciseMap The map of all available exercises
Definition at line 198 of file WorkoutPlanViewModel.cpp.
{
    clearScreen();
    printLabel("Exercises for " + day);
    displayMuscleGroupOptions(exerciseMap, day, exercises);
}
References clearScreen(), displayMuscleGroupOptions(), exerciseMap, printLabel(), and readFromCSV().
addExerciseToList()
void WorkoutPlanViewModel::addExerciseToList (const std::string & exerciseName, std::map< std::string, Exercise > & exerciseMap) private
Add a new exercise to the exercise list.
Parameters
exerciseName The name of the exercise to add
exerciseMap The map of all available exercises
Definition at line 679 of file WorkoutPlanViewModel.cpp.
{
    Exercise newExercise;
    newExercise.name = exerciseName;
    newExercise.muscleGroup = "Unknown"; // Or ask for this information
    newExercise.repetitions = 0; // Default value, should be updated
    newExercise.sets = 0; // Default value, should be updated
    newExercise.type = Exercise::ExerciseType::UNKNOWN; // Default value, should be updated
    exerciseMap[exerciseName] = newExercise;
    overwriteCSV("exercises.csv", exerciseMap);
}
References exerciseMap, Exercise::name, overwriteCSV(), readFromCSV(), and Exercise::UNKNOWN.
addExistingExerciseToDay()
void WorkoutPlanViewModel::addExistingExerciseToDay (const std::string & muscleGroup, std::vector< WorkoutPlan::ExerciseDetails > & exercises, std::map< std::string, Exercise > & exerciseMap) private
Add an existing exercise to the list of exercises for a specific day.
Parameters
muscleGroup The muscle group of the exercise
exercises The list of exercises for the day
exerciseMap The map of all available exercises
Definition at line 333 of file WorkoutPlanViewModel.cpp.
{
    clearScreen();
    printLabel("Exercises for muscle group - " + muscleGroup);
    std::vector<Exercise> filteredExercises;
    displayExercisesByMuscleGroup(exerciseMap, muscleGroup, filteredExercises);
    while (true)
    {
        std::cout << "\nEnter the number of the exercise to add or 'done' to finish: ";
        std::string input;
        std::getline(std::cin >> std::ws, input);
        if (input == "done")
        {
            break;
        }
        int exerciseChoice;
        try
        {
            size_t pos;
            exerciseChoice = std::stoi(input, &pos);
            if (pos < input.size())
            {
                std::cout << "Invalid input. Please enter a valid number.\n";
                continue;
            }
        }
        catch (const std::exception&)
        {
            std::cout << "Invalid input. Please enter a valid number.\n";
            continue;
        }
        if (exerciseChoice < 1 || exerciseChoice > filteredExercises.size())
        {
            std::cout << "Invalid choice. Please enter a valid number.\n";
            continue;
        }
        WorkoutPlan::ExerciseDetails ed;
        ed.exerciseName = filteredExercises[exerciseChoice - 1].name;
        ed.reps = filteredExercises[exerciseChoice - 1].repetitions;
        ed.sets = filteredExercises[exerciseChoice - 1].sets;
        exercises.push_back(ed);
        std::cout << "Exercise added.\n";
    }
}
References clearScreen(), displayExercisesByMuscleGroup(), exerciseMap, WorkoutPlan::ExerciseDetails::exerciseName, printLabel(), and readFromCSV().
deleteExerciseFromDay()
void WorkoutPlanViewModel::deleteExerciseFromDay (std::vector< WorkoutPlan::ExerciseDetails > & exercises) private
Delete an exercise from the list of exercises for a specific day.
Parameters
exercises The list of exercises for the day
Definition at line 413 of file WorkoutPlanViewModel.cpp.
{
    int deleteIndex;
    getValidInput(deleteIndex, "Enter the number of the exercise to delete (or 0 to cancel): ", 0, exercises.size());
    if (deleteIndex == 0)
    {
        return;
    }
    exercises.erase(exercises.begin() + deleteIndex - 1);
    std::cout << "Exercise deleted.\n";
}
References getValidInput(), and readFromCSV().
displayAllWorkoutPlans()
void WorkoutPlanViewModel::displayAllWorkoutPlans () const private
Display all workout plans.
Definition at line 66 of file WorkoutPlanViewModel.cpp.
{
    for (const auto& pair : workoutPlanMap)
    {
        displayWorkoutPlan(pair.second);
    }
}
References displayWorkoutPlan(), readFromCSV(), and workoutPlanMap.
displayCurrentExercisesForDay()
void WorkoutPlanViewModel::displayCurrentExercisesForDay (const std::string & day, const std::vector< WorkoutPlan::ExerciseDetails > & exercises) const private
Display the current exercises for a specific day.
Parameters
day The day of the week
exercises The list of exercises for the day
day The day to display exercises for
exercises The list of exercises for the day
Definition at line 181 of file WorkoutPlanViewModel.cpp.
{
    std::cout << "Current exercises for " << day << ":\n";
    for (size_t i = 0; i < exercises.size(); ++i)
    {
        std::cout << i + 1 << ". " << exercises[i].exerciseName << " - " << exercises[i].sets << "x" << exercises[i].reps << "\n";
    }
    printWindowSizedSeparator();
}
References printWindowSizedSeparator(), and readFromCSV().
displayExercisesByMuscleGroup()
void WorkoutPlanViewModel::displayExercisesByMuscleGroup (const std::map< std::string, Exercise > & exerciseMap, const std::string & muscleGroup, std::vector< Exercise > & filteredExercises) private
Display exercises filtered by muscle group.
Parameters
exerciseMap The map of all available exercises
muscleGroup The muscle group to filter by
filteredExercises The vector to store the filtered exercises
Definition at line 392 of file WorkoutPlanViewModel.cpp.
{
    size_t index = 1;
    for (const auto& pair : exerciseMap)
    {
        if (pair.second.muscleGroup == muscleGroup)
        {
            std::cout << index << ". " << pair.second.name << " (Type: " << Exercise::exerciseTypeToString(pair.second.type)
                << ", Muscle Group: " << pair.second.muscleGroup
                << ", Repetitions: " << pair.second.repetitions << ", Sets: " << pair.second.sets << ")\n";
            filteredExercises.push_back(pair.second);
            index++;
        }
    }
}
References exerciseMap, Exercise::exerciseTypeToString(), and readFromCSV().
displayExerciseTypes()
int WorkoutPlanViewModel::displayExerciseTypes () const private
Display the available exercise types.
Returns
int The number of exercise types available
Definition at line 310 of file WorkoutPlanViewModel.cpp.
{
    std::cout << "1. Strength\n";
    std::cout << "2. Hypertrophy\n";
    std::cout << "3. Endurance\n";
    std::cout << "4. Flexibility\n";
    std::cout << "5. Balance and Stability\n";
    std::cout << "6. Power\n";
    std::cout << "7. Functional\n";
    std::cout << "8. Aerobic\n";
    std::cout << "9. Anaerobic\n";
    std::cout << "10. Recovery and Regeneration\n";
    return 10;
}
displayMuscleGroupOptions()
void WorkoutPlanViewModel::displayMuscleGroupOptions (std::map< std::string, Exercise > & exerciseMap, const std::string & day, std::vector< WorkoutPlan::ExerciseDetails > & exercises) private
Display options for selecting a muscle group.
Display options for muscle groups when adding exercises.
Parameters
exerciseMap The map of all available exercises
day The day of the week
exercises The list of exercises for the day
exerciseMap The map of all available exercises
day The day to add exercises to
exercises The list of exercises for the day
Definition at line 212 of file WorkoutPlanViewModel.cpp.
{
    std::cout << "Enter exercises for " << day << " (choose muscle group, 'cancel' to stop adding exercises for this day, or 'done' to finish):\n";
    std::set<std::string> muscleGroups;
    for (const auto& pair : exerciseMap)
    {
        muscleGroups.insert(pair.second.muscleGroup);
    }
    std::vector<std::string> muscleGroupsVec(muscleGroups.begin(), muscleGroups.end());
    for (size_t i = 0; i < muscleGroupsVec.size(); ++i)
    {
        std::cout << i + 1 << ". " << muscleGroupsVec[i] << "\n";
    }
    size_t size = muscleGroupsVec.size();
    std::cout << ++size << ". Enter new exercise\n";
    std::cout << ++size << ". Done\n";
    std::cout << ++size << ". Cancel\n";
    int muscleGroupChoice;
    getValidInput(muscleGroupChoice, "Enter choice: ", 1, static_cast<int>(size));
    handleMuscleGroupChoice(muscleGroupChoice, muscleGroupsVec, day, exercises, exerciseMap);
}
References exerciseMap, getValidInput(), handleMuscleGroupChoice(), and readFromCSV().
displayWorkoutPlan()
void WorkoutPlanViewModel::displayWorkoutPlan (const WorkoutPlan & plan) const private
Display the details of a specific workout plan.
Display the details of a given workout plan.
Parameters
plan The workout plan to display
Definition at line 110 of file WorkoutPlanViewModel.cpp.
{
    std::cout << "Name: " << plan.name << ", Type: " << WorkoutPlan::planTypeToString(plan.type) << "\n";
    for (const auto& day : DAYS_OF_WEEK)
    {
        auto it = plan.weeklyPlan.find(day);
        if (it != plan.weeklyPlan.end())
        {
            std::cout << "  " << day << ":\n";
            if (it->second.empty())
            {
                std::cout << "    Rest Day\n";
            }
            else
            {
                for (const auto& exercise : it->second)
                {
                    std::cout << "    " << exercise.exerciseName << " - " << exercise.sets << "x" << exercise.reps << "\n";
                }
            }
        }
    }
    printWindowSizedSeparator();
}
References DAYS_OF_WEEK, WorkoutPlan::planTypeToString(), printWindowSizedSeparator(), and readFromCSV().
displayWorkoutPlansByType()
void WorkoutPlanViewModel::displayWorkoutPlansByType () const private
Display workout plans filtered by type.
Definition at line 77 of file WorkoutPlanViewModel.cpp.
{
    std::cout << "Workout Plan Types:\n";
    std::cout << "1. Strength\n";
    std::cout << "2. Power\n";
    std::cout << "3. Hypertrophy\n";
    std::cout << "4. Conditioning\n";
    std::cout << "5. Push\n";
    std::cout << "6. Pull\n";
    std::cout << "7. Legs\n";
    printWindowSizedSeparator();
    int typeChoice;
    getValidInput(typeChoice, "Enter choice: ", 1, 7);
    WorkoutPlan::PlanType selectedType = static_cast<WorkoutPlan::PlanType>(typeChoice - 1);
    for (const auto& pair : workoutPlanMap)
    {
        const auto& plan = pair.second;
        if (plan.type == selectedType)
        {
            displayWorkoutPlan(plan);
        }
    }
}
References displayWorkoutPlan(), getValidInput(), printWindowSizedSeparator(), readFromCSV(), and workoutPlanMap.
displayWorkoutPlanTypes()
void WorkoutPlanViewModel::displayWorkoutPlanTypes () const private
Display the available workout plan types.
Definition at line 467 of file WorkoutPlanViewModel.cpp.
{
    std::cout << "1. Strength\n";
    std::cout << "2. Hypertrophy\n";
    std::cout << "3. Conditioning\n";
    std::cout << "4. Push\n";
    std::cout << "5. Pull\n";
    std::cout << "6. Legs\n";
}
editDailyExercises()
void WorkoutPlanViewModel::editDailyExercises (const std::string & day, std::vector< WorkoutPlan::ExerciseDetails > & exercises, std::map< std::string, Exercise > & exerciseMap) private
Edit exercises for a specific day in the workout plan.
Edit the daily exercises for a specific day.
Parameters
day The day of the week
exercises The list of exercises for the day
exerciseMap The map of all available exercises
day The day to edit exercises for
exercises The list of exercises for the day
exerciseMap The map of all available exercises
Definition at line 144 of file WorkoutPlanViewModel.cpp.
{
    bool modifyingExercises = true;
    while (modifyingExercises)
    {
        clearScreen();
        printLabel("Exercises for " + day);
        displayCurrentExercisesForDay(day, exercises);
        std::cout << "Options:\n1. Add an exercise\n2. Delete an exercise\n3. Done\n";
        int exerciseChoice;
        getValidInput(exerciseChoice, "Enter choice: ", 1, 3);
        switch (exerciseChoice)
        {
        case 1:
            addExerciseToDay(day, exercises, exerciseMap);
            break;
        case 2:
            deleteExerciseFromDay(exercises);
            break;
        case 3:
            modifyingExercises = false;
            break;
        default:
            break;
        }
    }
}
References addExerciseToDay(), clearScreen(), deleteExerciseFromDay(), displayCurrentExercisesForDay(), exerciseMap, getValidInput(), printLabel(), and readFromCSV().
handleMuscleGroupChoice()
void WorkoutPlanViewModel::handleMuscleGroupChoice (int choice, const std::vector< std::string > & muscleGroupsVec, const std::string & day, std::vector< WorkoutPlan::ExerciseDetails > & exercises, std::map< std::string, Exercise > & exerciseMap) private
Handle the choice of muscle group selection.
Handle the muscle group choice when adding exercises.
Parameters
choice The selected option
muscleGroupsVec The list of muscle groups
day The day of the week
exercises The list of exercises for the day
exerciseMap The map of all available exercises
choice The user's choice for the muscle group
muscleGroupsVec The vector of muscle groups
day The day to add exercises to
exercises The list of exercises for the day
exerciseMap The map of all available exercises
Definition at line 247 of file WorkoutPlanViewModel.cpp.
{
    if (choice == muscleGroupsVec.size() + 1)
    {
        addCustomExercise(day, exercises, exerciseMap);
    }
    else if (choice == muscleGroupsVec.size() + 2)
    {
        return;
    }
    else if (choice == muscleGroupsVec.size() + 3)
    {
        std::cout << "Cancelling exercise addition.\n";
        return;
    }
    else
    {
        addExistingExerciseToDay(muscleGroupsVec[choice - 1], exercises, exerciseMap);
    }
}
References addCustomExercise(), addExistingExerciseToDay(), exerciseMap, and readFromCSV().
importFromFile()
void WorkoutPlanViewModel::importFromFile (const std::string & filename) override virtual
Import workout plans from a CSV file.
Parameters
filename The name of the CSV file to import workout plans from
Implements ViewModel.
Definition at line 611 of file WorkoutPlanViewModel.cpp.
{
    auto items = readFromCSV<WorkoutPlan>(filename);
    for (const auto& item : items)
    {
        if (workoutPlanMap.find(item.first) != workoutPlanMap.end())
        {
            overwriteWorkoutPlan(item);
        }
        else
        {
            workoutPlanMap[item.first] = item.second;
        }
        for (const auto& day : item.second.weeklyPlan)
        {
            for (const auto& exercise : day.second)
            {
                if (exerciseMap.find(exercise.exerciseName) == exerciseMap.end())
                {
                    addExerciseToList(exercise.exerciseName, exerciseMap);
                }
            }
        }
    }
    overwriteCSV("workout_plans.csv", workoutPlanMap);
    overwriteCSV("exercises.csv", exerciseMap);
}
References addExerciseToList(), exerciseMap, filename, overwriteCSV(), overwriteWorkoutPlan(), readFromCSV(), and workoutPlanMap.
modify()
void WorkoutPlanViewModel::modify () override virtual
Modify an existing workout plan.
Implements ViewModel.
Definition at line 480 of file WorkoutPlanViewModel.cpp.
{
    if (workoutPlanMap.empty())
    {
        std::cout << "No workout plans available to modify.\n";
        return;
    }
    std::cout << "Select a workout plan to modify:\n";
    std::vector<std::string> planNames;
    int index = 1;
    for (const auto& pair : workoutPlanMap)
    {
        std::cout << index << ". " << pair.first << "\n";
        planNames.push_back(pair.first);
        ++index;
    }
    std::cout << index << ". Cancel\n";
    int choice;
    getValidInput(choice, "Enter choice: ", 1, planNames.size() + 1);
    if (choice == index)
    {
        std::cout << "Modify operation cancelled.\n";
        return;
    }
    std::string selectedPlanName = planNames[choice - 1];
    auto& selectedPlan = workoutPlanMap[selectedPlanName];
    modifyWorkoutPlan(selectedPlan);
    workoutPlanMap[selectedPlanName] = selectedPlan;
    overwriteCSV(filename, workoutPlanMap);
    std::cout << "Workout plan modified.\n";
}
References filename, getValidInput(), modifyWorkoutPlan(), overwriteCSV(), readFromCSV(), and workoutPlanMap.
modifyWorkoutPlan()
void WorkoutPlanViewModel::modifyWorkoutPlan (WorkoutPlan & plan) private
Modify the details of a workout plan.
Parameters
plan The workout plan to modify
Definition at line 523 of file WorkoutPlanViewModel.cpp.
{
    std::string newName;
    int typeChoice;
    std::cout << "Enter new workout plan name (or press enter to keep current): ";
    std::getline(std::cin, newName);
    if (!newName.empty())
    {
        plan.name = newName;
    }
    std::cout << "\nCurrent workout plan type: " << WorkoutPlan::planTypeToString(plan.type) << "\n";
    std::cout << "Select new workout plan type (or press enter to keep current):\n";
    displayWorkoutPlanTypes();
    std::string typeInput;
    std::getline(std::cin, typeInput);
    if (!typeInput.empty())
    {
        typeChoice = std::stoi(typeInput);
        if (typeChoice >= 1 && typeChoice <= 6)
        {
            plan.type = static_cast<WorkoutPlan::PlanType>(typeChoice - 1);
            std::cout << "Current workout plan type: " << WorkoutPlan::planTypeToString(plan.type) << "\n";
            std::cout << "Press enter to continue.\n";
            std::cin.ignore();
        }
        else
        {
            std::cout << "Invalid choice, keeping the current type.\n";
            std::cout << "Current workout plan type: " << WorkoutPlan::planTypeToString(plan.type) << "\n";
            std::cout << "Press enter to continue.\n";
            std::cin.ignore();
        }
    }
    for (const auto& day : DAYS_OF_WEEK)
    {
        std::vector<WorkoutPlan::ExerciseDetails> exercises = plan.weeklyPlan[day];
        editDailyExercises(day, exercises, exerciseMap);
        plan.weeklyPlan[day] = exercises;
    }
}
References DAYS_OF_WEEK, displayWorkoutPlanTypes(), editDailyExercises(), exerciseMap, WorkoutPlan::planTypeToString(), and readFromCSV().
overwriteWorkoutPlan()
void WorkoutPlanViewModel::overwriteWorkoutPlan (const std::pair< std::string, WorkoutPlan > & item) private
Overwrite an existing workout plan with a new one.
Parameters
item The new workout plan to overwrite with
Definition at line 647 of file WorkoutPlanViewModel.cpp.
{
    const auto& currentPlan = workoutPlanMap[item.first];
    const auto& newPlan = item.second;
    std::cout << "Workout plan '" << item.first << "' already exists.\n";
    std::cout << "Current plan:\n";
    displayWorkoutPlan(currentPlan);
    std::cout << "New plan:\n";
    displayWorkoutPlan(newPlan);
    if (confirmOverwrite(workoutPlanMap, item.first))
    {
        workoutPlanMap[item.first] = newPlan;
    }
}
References ViewModel::confirmOverwrite(), displayWorkoutPlan(), readFromCSV(), and workoutPlanMap.
reload()
void WorkoutPlanViewModel::reload () override virtual
Reload workout plans and exercises from CSV files.
Implements ViewModel.
Definition at line 667 of file WorkoutPlanViewModel.cpp.
{
    exerciseMap = readFromCSV<Exercise>("exercises.csv");
    workoutPlanMap = readFromCSV<WorkoutPlan>(filename);
}
References exerciseMap, filename, readFromCSV(), and workoutPlanMap.
remove()
void WorkoutPlanViewModel::remove () override virtual
Remove an existing workout plan.
Implements ViewModel.
Definition at line 571 of file WorkoutPlanViewModel.cpp.
{
    if (workoutPlanMap.empty())
    {
        std::cout << "No workout plans available to delete.\n";
        return;
    }
    std::cout << "Select a workout plan to delete:\n";
    std::vector<std::string> planNames;
    int index = 1;
    for (const auto& pair : workoutPlanMap)
    {
        std::cout << index << ". " << pair.first << "\n";
        planNames.push_back(pair.first);
        ++index;
    }
    std::cout << index << ". Cancel\n";
    int choice;
    getValidInput(choice, "Enter choice: ", 1, planNames.size() + 1);
    if (choice == index)
    {
        std::cout << "Delete operation cancelled.\n";
        return;
    }
    std::string selectedPlanName = planNames[choice - 1];
    workoutPlanMap.erase(selectedPlanName);
    overwriteCSV(filename, workoutPlanMap);
    std::cout << "Workout plan '" << selectedPlanName << "' deleted.\n";
}
References filename, getValidInput(), overwriteCSV(), readFromCSV(), and workoutPlanMap.
view()
void WorkoutPlanViewModel::view () override virtual
Display the available workout plans.
Display the workout plans based on user choice.
Implements ViewModel.
Definition at line 35 of file WorkoutPlanViewModel.cpp.
{
    if (workoutPlanMap.empty())
    {
        std::cout << "No workout plans available.\n";
        return;
    }
    int viewChoice;
    int count = printViewOptions();
    getValidInput(viewChoice, "Enter choice: ", 1, count);
    if (viewChoice == 3)
    {
        return;
    }
    if (viewChoice == 1)
    {
        displayAllWorkoutPlans();
    }
    else if (viewChoice == 2)
    {
        displayWorkoutPlansByType();
    }
}
References displayAllWorkoutPlans(), displayWorkoutPlansByType(), getValidInput(), printViewOptions(), readFromCSV(), and workoutPlanMap.
Member Data Documentation
exerciseMap
std::map<std::string, Exercise> WorkoutPlanViewModel::exerciseMap private
The map of exercises.
Definition at line 56 of file WorkoutPlanViewModel.h.
filename
std::string WorkoutPlanViewModel::filename private
The filename to read/write workout plans.
Definition at line 54 of file WorkoutPlanViewModel.h.
workoutPlanMap
std::map<std::string, WorkoutPlan> WorkoutPlanViewModel::workoutPlanMap private
The map of workout plans.
Definition at line 55 of file WorkoutPlanViewModel.h.
The documentation for this class was generated from the following files:
WorkoutPlanViewModel.h
WorkoutPlanViewModel.cpp