FitnessApp: FoodViewModel Class Reference
FoodViewModel Class Reference
ViewModel class for handling food items.
#include <FoodViewModel.h>
Public Member Functions
FoodViewModel (const std::string &file)
Construct a new FoodViewModel object.
void view () override
View the food items.
void add () override
Add a new food item.
void modify () override
Modify an existing food item.
void remove () override
Remove a food item.
void importFromFile (const std::string &filename) override
Import food items from a file.
void reload () override
Reload the food items from the CSV file.
Public Member Functions inherited from ViewModel
template<typename T >
bool confirmOverwrite (std::map< std::string, T > &itemMap, const std::string &name)
Prompts the user to confirm overwriting an existing item.
Private Member Functions
void displayCategoriesOfFoodItem (const FoodItem &foodItem) const
Display the categories of a given food item.
void displayFoodItem (const FoodItem &foodItem) const
Display the details of a given food item.
void displayFoodItems (const std::map< std::string, FoodItem > &foodMap) const
Display the list of food items.
void displayFoodItemsByCategories ()
Display food items filtered by categories.
void displayCategoriesOfFoodItemMap (const std::vector< std::string > &categoryVec) const
Display the categories of food items in a map.
void handleCategorySelection (std::map< std::string, FoodItem > &filteredFoodItems)
Handle the selection of a category and filter food items accordingly.
void handleFoodModification (FoodItem &foodItem)
Handle the modification of a food item.
void handleFoodDeletion (std::map< std::string, FoodItem > &filteredFoodItems)
Handle the deletion of food items.
void confirmAndDeleteFoodItem (const std::string &name)
Confirm and delete a food item from the food item map.
void modifyCategories (FoodItem &foodItem)
Modify the categories of a food item.
Private Attributes
std::string filename
The filename containing the food items.
std::map< std::string, FoodItem > foodItemMap
Map to store food items.
Detailed Description
ViewModel class for handling food items.
This class provides functionalities to view, add, modify, remove, and import food items from a file. It inherits from the ViewModel base class.
Definition at line 16 of file FoodViewModel.h.
Constructor & Destructor Documentation
FoodViewModel()
FoodViewModel::FoodViewModel (const std::string & file)
Construct a new FoodViewModel object.
Construct a new FoodViewModel::FoodViewModel object.
Parameters
file The filename to read food items from.
file The filename to read food items from
Definition at line 11 of file FoodViewModel.cpp.
                                                  : filename(file)
{
    foodItemMap = readFromCSV<FoodItem>(filename);
}
References filename, foodItemMap, and readFromCSV().
Member Function Documentation
add()
void FoodViewModel::add () override virtual
Add a new food item.
Add a new food item to the food item map.
This method is used to add a new food item to the foodItemMap.
Implements ViewModel.
Definition at line 144 of file FoodViewModel.cpp.
{
    std::string name;
    std::set<std::string> categories;
    std::cout << "Enter food name: ";
    std::getline(std::cin >> std::ws, name);
    // Check if the food item already exists and confirm overwrite if it does
    if (!confirmOverwrite(foodItemMap, name))
    {
        return;
    }
    FoodItem foodItem;
    foodItem.name = name;
    modifyCategories(foodItem);
    getValidInput(foodItem.calories, "Enter calories per 100 grams: ");
    getValidInput(foodItem.protein, "Enter protein per 100 grams: ");
    getValidInput(foodItem.carbohydrates, "Enter carbohydrates per 100 grams: ");
    getValidInput(foodItem.fats, "Enter fats per 100 grams: ");
    getOptionalInput(foodItem.portion, "Enter portion size in grams (or press enter to skip): ");
    foodItemMap[name] = foodItem;
    writeToCSV(filename, foodItem);
}
References ViewModel::confirmOverwrite(), filename, foodItemMap, getOptionalInput(), getValidInput(), modifyCategories(), FoodItem::name, readFromCSV(), and writeToCSV().
confirmAndDeleteFoodItem()
void FoodViewModel::confirmAndDeleteFoodItem (const std::string & name) private
Confirm and delete a food item from the food item map.
Parameters
name The name of the food item to delete.
name The name of the food item to delete
Definition at line 303 of file FoodViewModel.cpp.
{
    const auto& foodItem = foodItemMap[name];
    std::string confirm;
    do
    {
        std::cout << "Are you sure you want to delete " << foodItem.name << " (Categories: ";
        displayCategoriesOfFoodItem(foodItem);
        std::cout << ", Calories: " << foodItem.calories
            << ", Protein: " << foodItem.protein << " g, Carbohydrates: " << foodItem.carbohydrates
            << " g, Fats: " << foodItem.fats << " g, Portion: " << foodItem.portion << " g)? (yes/no): ";
        std::getline(std::cin >> std::ws, confirm);
    } while (confirm != "yes" && confirm != "no");
    if (confirm == "yes")
    {
        foodItemMap.erase(name);
        overwriteCSV(filename, foodItemMap);
        std::cout << "Food item deleted.\n";
    }
    else
    {
        std::cout << "Food item not deleted.\n";
    }
}
References displayCategoriesOfFoodItem(), filename, foodItemMap, overwriteCSV(), and readFromCSV().
displayCategoriesOfFoodItem()
void FoodViewModel::displayCategoriesOfFoodItem (const FoodItem & foodItem) const private
Display the categories of a given food item.
Parameters
foodItem The food item whose categories will be displayed.
foodItem The food item whose categories will be displayed
Definition at line 21 of file FoodViewModel.cpp.
{
    std::cout << "Categories: ";
    for (auto it = foodItem.categories.begin(); it != foodItem.categories.end(); ++it)
    {
        if (it != foodItem.categories.begin())
        {
            std::cout << "; ";
        }
        std::cout << *it;
    }
}
References readFromCSV().
displayCategoriesOfFoodItemMap()
void FoodViewModel::displayCategoriesOfFoodItemMap (const std::vector< std::string > & categories) const private
Display the categories of food items in a map.
Display the categories of food items.
Parameters
categoryVec The vector of categories to be displayed.
categories The vector of categories to be displayed
Definition at line 97 of file FoodViewModel.cpp.
{
    for (size_t i = 0; i < categories.size(); ++i)
    {
        std::cout << i + 1 << ". " << categories[i] << "\n";
    }
}
References readFromCSV().
displayFoodItem()
void FoodViewModel::displayFoodItem (const FoodItem & foodItem) const private
Display the details of a given food item.
Parameters
foodItem The food item whose details will be displayed.
foodItem The food item whose details will be displayed
Definition at line 39 of file FoodViewModel.cpp.
{
    std::cout << "Name: " << foodItem.name << ", ";
    displayCategoriesOfFoodItem(foodItem);
    std::cout << ", Calories: " << foodItem.calories
        << " kcal, Protein: " << foodItem.protein << " g, Carbohydrates: "
        << foodItem.carbohydrates << " g, Fats: " << foodItem.fats << " g, Portion: " << foodItem.portion << " g\n";
}
References displayCategoriesOfFoodItem(), and readFromCSV().
displayFoodItems()
void FoodViewModel::displayFoodItems (const std::map< std::string, FoodItem > & foodMap) const private
Display the list of food items.
Parameters
foodMap The map containing the food items to be displayed.
foodMap The map containing the food items to be displayed
Definition at line 53 of file FoodViewModel.cpp.
{
    if (foodMap.empty())
    {
        std::cout << "No food items to display.\n";
        return;
    }
    std::cout << "Food Item List:\n";
    printWindowSizedSeparator();
    std::size_t index = 1;
    for (const auto& pair : foodMap)
    {
        const auto& foodItem = pair.second;
        std::cout << index++ << ". ";
        displayFoodItem(foodItem);
        printWindowSizedSeparator();
    }
}
References displayFoodItem(), printWindowSizedSeparator(), and readFromCSV().
displayFoodItemsByCategories()
void FoodViewModel::displayFoodItemsByCategories () private
Display food items filtered by categories.
Definition at line 108 of file FoodViewModel.cpp.
{
    std::map<std::string, FoodItem> filteredFoodItems;
    handleCategorySelection(filteredFoodItems);
    displayFoodItems(filteredFoodItems);
}
References displayFoodItems(), handleCategorySelection(), and readFromCSV().
handleCategorySelection()
void FoodViewModel::handleCategorySelection (std::map< std::string, FoodItem > & filteredFoodItems) private
Handle the selection of a category and filter food items accordingly.
Parameters
filteredFoodItems The map to store the filtered food items.
filteredFoodItems The map to store the filtered food items
Definition at line 334 of file FoodViewModel.cpp.
{
    std::vector<std::string> categories = getFoodItemCategories(foodItemMap);
    displayCategoriesOfFoodItemMap(categories);
    int categoryChoice;
    getValidInput(categoryChoice, "Select a category by number: ", 1, static_cast<int>(categories.size()));
    std::string selectedCategory = categories[categoryChoice - 1];
    for (const auto& pair : foodItemMap)
    {
        if (pair.second.categories.find(selectedCategory) != pair.second.categories.end())
        {
            filteredFoodItems[pair.first] = pair.second;
        }
    }
}
References displayCategoriesOfFoodItemMap(), foodItemMap, getFoodItemCategories(), getValidInput(), and readFromCSV().
handleFoodDeletion()
void FoodViewModel::handleFoodDeletion (std::map< std::string, FoodItem > & filteredFoodItems) private
Handle the deletion of food items.
Handle the deletion of a food item.
Parameters
filteredFoodItems The map of filtered food items to be displayed and deleted.
filteredFoodItems The map to store the filtered food items
Definition at line 357 of file FoodViewModel.cpp.
{
    displayFoodItems(filteredFoodItems);
    int cancelIndex = static_cast<int>(filteredFoodItems.size()) + 1;
    std::cout << cancelIndex << ". Cancel\n";
    int choice;
    getValidInput(choice, "Enter the number of the food item to delete: ", 1, cancelIndex);
    if (choice == cancelIndex)
    {
        std::cout << "Operation cancelled.\n";
        return;
    }
    std::vector<std::string> names;
    for (const auto& pair : filteredFoodItems)
    {
        names.push_back(pair.first);
    }
    confirmAndDeleteFoodItem(names[choice - 1]);
}
References confirmAndDeleteFoodItem(), displayFoodItems(), getValidInput(), and readFromCSV().
handleFoodModification()
void FoodViewModel::handleFoodModification (FoodItem & foodItem) private
Handle the modification of a food item.
Parameters
foodItem The food item to be modified.
foodItem The food item to be modified
Definition at line 221 of file FoodViewModel.cpp.
{
    std::string newName;
    std::cout << "Enter new food name (or press enter to keep current): ";
    std::getline(std::cin, newName);
    if (!newName.empty())
    {
        foodItem.name = newName;
    }
    modifyCategories(foodItem);
    getOptionalInput(foodItem.calories, "Enter new calories per 100 grams (or press enter to keep current): ");
    getOptionalInput(foodItem.protein, "Enter new protein per 100 grams (or press enter to keep current): ");
    getOptionalInput(foodItem.carbohydrates, "Enter new carbohydrates per 100 grams (or press enter to keep current): ");
    getOptionalInput(foodItem.fats, "Enter new fats per 100 grams (or press enter to keep current): ");
    getOptionalInput(foodItem.portion, "Enter new portion size in grams (or press enter to keep current): ");
}
References getOptionalInput(), modifyCategories(), and readFromCSV().
importFromFile()
void FoodViewModel::importFromFile (const std::string & filename) override virtual
Import food items from a file.
Import food items from a CSV file.
This method is used to import food items from a specified CSV file.
Parameters
filename The name of the file to import food items from.
filename The name of the CSV file to import food items from
Implements ViewModel.
Definition at line 423 of file FoodViewModel.cpp.
{
    auto items = readFromCSV<FoodItem>(filename);
    for (const auto& item : items)
    {
        auto it = foodItemMap.find(item.first);
        if (it != foodItemMap.end())
        {
            clearScreen();
            const auto& currentFoodItem = it->second;
            const auto& newFoodItem = item.second;
            std::cout << "Food item '" << item.first << "' already exists.\n";
            std::cout << "Current food item:\n";
            std::cout << "  Name: " << currentFoodItem.name << "\n";
            std::cout << "  Categories: ";
            displayCategoriesOfFoodItem(currentFoodItem);
            std::cout << "\n  Calories: " << currentFoodItem.calories << "\n";
            std::cout << "  Protein: " << currentFoodItem.protein << "\n";
            std::cout << "  Carbohydrates: " << currentFoodItem.carbohydrates << "\n";
            std::cout << "  Fats: " << currentFoodItem.fats << "\n";
            std::cout << "  Portion: " << currentFoodItem.portion << " g\n";
            std::cout << "New food item:\n";
            std::cout << "  Name: " << newFoodItem.name << "\n";
            std::cout << "  Categories: ";
            displayCategoriesOfFoodItem(newFoodItem);
            std::cout << "\n  Calories: " << newFoodItem.calories << "\n";
            std::cout << "  Protein: " << newFoodItem.protein << "\n";
            std::cout << "  Carbohydrates: " << newFoodItem.carbohydrates << "\n";
            std::cout << "  Fats: " << newFoodItem.fats << "\n";
            std::cout << "  Portion: " << newFoodItem.portion << " g\n";
            std::string choice;
            do
            {
                std::cout << "Do you want to overwrite the current food item with the new one? (yes/no): ";
                std::getline(std::cin >> std::ws, choice);
            } while (choice != "yes" && choice != "no");
            if (choice == "yes")
            {
                foodItemMap[item.first] = newFoodItem;
            }
        }
        else
        {
            foodItemMap[item.first] = item.second;
        }
    }
    overwriteCSV("food_items.csv", foodItemMap);
}
References clearScreen(), displayCategoriesOfFoodItem(), filename, foodItemMap, overwriteCSV(), and readFromCSV().
modify()
void FoodViewModel::modify () override virtual
Modify an existing food item.
This method is used to modify the details of an existing food item.
Implements ViewModel.
Definition at line 243 of file FoodViewModel.cpp.
{
    if (foodItemMap.empty())
    {
        std::cout << "No food items to modify.\n";
        return;
    }
    std::cout << "Do you want to display all food items or by category?\n";
    std::cout << "1. Display all\n";
    std::cout << "2. Display by category\n";
    int choice;
    getValidInput(choice, "Enter choice: ", 1, 2);
    std::map<std::string, FoodItem> filteredFoodItems;
    if (choice == 1)
    {
        filteredFoodItems = foodItemMap;
    }
    else if (choice == 2)
    {
        handleCategorySelection(filteredFoodItems);
    }
    else
    {
        std::cout << "Invalid choice.\n";
        return;
    }
    std::cout << "Choose a food item to modify:\n";
    std::vector<std::string> names;
    for (const auto& pair : filteredFoodItems)
    {
        names.push_back(pair.first);
    }
    displayFoodItems(filteredFoodItems);
    std::size_t cancelIndex = filteredFoodItems.size() + 1;
    std::cout << cancelIndex << ". Cancel\n";
    getValidInput(choice, "Enter the number of the food item to modify: ", 1, static_cast<int>(cancelIndex));
    if (choice == cancelIndex)
    {
        std::cout << "Operation cancelled.\n";
        return;
    }
    handleFoodModification(foodItemMap[names[choice - 1]]);
    overwriteCSV(filename, foodItemMap);
    std::cout << "Food modified.\n";
}
References displayFoodItems(), filename, foodItemMap, getValidInput(), handleCategorySelection(), handleFoodModification(), overwriteCSV(), and readFromCSV().
modifyCategories()
void FoodViewModel::modifyCategories (FoodItem & foodItem) private
Modify the categories of a food item.
Parameters
foodItem The food item whose categories will be modified.
foodItem The food item whose categories will be modified
Definition at line 178 of file FoodViewModel.cpp.
{
    while (true)
    {
        std::string categoryChoice;
        std::cout << "Current ";
        displayCategoriesOfFoodItem(foodItem);
        std::cout << "\nOptions:\n1. Add a category\n2. Delete a category\n3. Done\n";
        std::cout << "Enter choice: ";
        std::getline(std::cin, categoryChoice);
        if (categoryChoice == "1")
        {
            std::string newCategory;
            std::cout << "Enter new category: ";
            std::getline(std::cin >> std::ws, newCategory);
            foodItem.categories.insert(toLower(newCategory));
        }
        else if (categoryChoice == "2")
        {
            int deleteChoice;
            std::vector<std::string> categoryList(foodItem.categories.begin(), foodItem.categories.end());
            getValidInput(deleteChoice, "Enter the number of the category to delete: ", 1, static_cast<int>(categoryList.size()));
            foodItem.categories.erase(categoryList[deleteChoice - 1]);
        }
        else if (categoryChoice == "3")
        {
            break;
        }
        else
        {
            std::cout << "Invalid choice. Please enter 1, 2, or 3.\n";
        }
    }
}
References displayCategoriesOfFoodItem(), getValidInput(), readFromCSV(), and toLower().
reload()
void FoodViewModel::reload () override virtual
Reload the food items from the CSV file.
This method reloads the food items from the CSV file to refresh the foodItemMap.
Implements ViewModel.
Definition at line 478 of file FoodViewModel.cpp.
{
    foodItemMap = readFromCSV<FoodItem>(filename);
}
References filename, foodItemMap, and readFromCSV().
remove()
void FoodViewModel::remove () override virtual
Remove a food item.
Remove a food item from the food item map.
This method is used to remove a food item from the foodItemMap.
Implements ViewModel.
Definition at line 385 of file FoodViewModel.cpp.
{
    if (foodItemMap.empty())
    {
        std::cout << "No food items to delete.\n";
        return;
    }
    std::cout << "Do you want to display all food items or by category?\n";
    std::cout << "1. Display all\n";
    std::cout << "2. Display by category\n";
    int choice;
    getValidInput(choice, "Enter choice: ", 1, 2);
    std::map<std::string, FoodItem> filteredFoodItems;
    if (choice == 1)
    {
        filteredFoodItems = foodItemMap;
    }
    else if (choice == 2)
    {
        handleCategorySelection(filteredFoodItems);
    }
    else
    {
        std::cout << "Invalid choice.\n";
        return;
    }
    handleFoodDeletion(filteredFoodItems);
}
References foodItemMap, getValidInput(), handleCategorySelection(), handleFoodDeletion(), and readFromCSV().
view()
void FoodViewModel::view () override virtual
View the food items.
Display the available food items based on user choice (all or by category)
This method is used to display food items either by categories or all food items.
Implements ViewModel.
Definition at line 118 of file FoodViewModel.cpp.
{
    std::cout << "Do you want to view all food items or by category?\n";
    std::cout << "1. View all\n";
    std::cout << "2. View by category\n";
    int choice;
    getValidInput(choice, "Enter choice: ", 1, 2);
    if (choice == 1)
    {
        displayFoodItems(foodItemMap);
    }
    else if (choice == 2)
    {
        displayFoodItemsByCategories();
    }
    else
    {
        std::cout << "Invalid choice.\n";
    }
}
References displayFoodItems(), displayFoodItemsByCategories(), foodItemMap, getValidInput(), and readFromCSV().
Member Data Documentation
filename
std::string FoodViewModel::filename private
The filename containing the food items.
Definition at line 72 of file FoodViewModel.h.
foodItemMap
std::map<std::string, FoodItem> FoodViewModel::foodItemMap private
Map to store food items.
Definition at line 73 of file FoodViewModel.h.
The documentation for this class was generated from the following files:
FoodViewModel.h
FoodViewModel.cpp