FitnessApp: NutritionPlanViewModel Class Reference
NutritionPlanViewModel Class Reference
ViewModel class for managing and manipulating nutrition plans.
#include <NutritionPlanViewModel.h>
Public Member Functions
NutritionPlanViewModel (const std::string &filename)
Constructor to initialize the NutritionPlanViewModel with a file name.
void view () override
Display the nutrition plans.
void add () override
Add a new nutrition plan.
void modify () override
Modify an existing nutrition plan.
void remove () override
Remove a nutrition plan.
void importFromFile (const std::string &filename) override
Import nutrition plans from a file.
void reload () override
Reload the nutrition plans and food items from the CSV files.
Public Member Functions inherited from ViewModel
template<typename T >
bool confirmOverwrite (std::map< std::string, T > &itemMap, const std::string &name)
Prompts the user to confirm overwriting an existing item.
Private Member Functions
void modifyNutritionPlan (NutritionPlan &selectedPlan, const std::map< std::string, FoodItem > &foodItemMap)
Modify a nutrition plan.
NutritionPlan generateNextPlan (float targetCalories, float targetProtein)
Generate the next nutrition plan based on the target calories and protein.
void shufflePlanNames ()
Shuffle the plan names.
void calculateCurrentValues (const NutritionPlan &plan, float &currentCalories, float &currentProtein)
Calculate the current calories and protein in a plan.
void adjustPortions (NutritionPlan &plan, float &currentCalories, float &currentProtein, float target, int maxIterations, bool isReducing)
Adjust portions of the nutrition plan.
void adjustProtein (NutritionPlan &plan, float &currentProtein, float targetProtein, float &currentCalories, int maxIterations, bool isIncreasing)
Adjust the protein intake in the nutrition plan.
void adjustNonProteinItems (NutritionPlan &plan, float &currentCalories, float targetCalories, float &currentProtein, int maxIterations)
Add non-protein items to match the caloric needs.
void finalAdjustment (NutritionPlan &plan, float &currentCalories, float targetCalories, float &currentProtein, float targetProtein)
Perform final adjustments to ensure the values are within the goals.
void displayCurrentFoods (const std::vector< std::pair< FoodItem, float > > &mealItems)
Display current foods in a meal.
void handleAddFood (NutritionPlan &selectedPlan, const std::map< std::string, FoodItem > &foodItemMap, const std::string &mealName)
Handle the addition of a food item to a meal.
void handleRemoveFood (NutritionPlan &selectedPlan, const std::string &mealName)
Handle the removal of a food item from a meal.
std::vector< std::string > getAvailableCategories (const std::map< std::string, FoodItem > &foodItemMap)
Get the available categories from the food item map.
void viewAllPlans ()
View all nutrition plans.
void viewPersonalizedPlan ()
View a personalized nutrition plan based on goals.
void displayPlan (const NutritionPlan &plan)
Display a nutrition plan.
std::string selectPlan (const std::string &action)
Select a nutrition plan for modification or deletion.
void confirmAndRemovePlan (const std::string &selectedPlanName)
Confirm and remove a selected nutrition plan.
void printFoodItem (const FoodItem &foodItem, float quantity)
Print a food item.
void printMealTotal (const std::string &mealName, TotalNutrients totalMeal)
Print the total nutrients for a meal.
void printPlanTotal (TotalNutrients totalPlan)
Print the total nutrients for the entire plan.
Private Attributes
std::string filename
std::map< std::string, NutritionPlan > nutritionPlanMap
std::map< std::string, FoodItem > foodItemMap
size_t currentPlanIndex = 0
std::vector< std::string > shuffledPlanNames
const int proteinPerHundredGrams = 15
Detailed Description
ViewModel class for managing and manipulating nutrition plans.
Definition at line 27 of file NutritionPlanViewModel.h.
Constructor & Destructor Documentation
NutritionPlanViewModel()
NutritionPlanViewModel::NutritionPlanViewModel (const std::string & filename)
Constructor to initialize the NutritionPlanViewModel with a file name.
Constructor to initialize NutritionPlanViewModel with a filename.
Parameters
filename The name of the file containing the nutrition plans.
filename The filename from which to load nutrition plans.
Definition at line 14 of file NutritionPlanViewModel.cpp.
                                                                        : filename(filename)
{
    reload();
}
References reload().
Member Function Documentation
add()
void NutritionPlanViewModel::add () override virtual
Add a new nutrition plan.
Implements ViewModel.
Definition at line 427 of file NutritionPlanViewModel.cpp.
{
    std::string name;
    std::map<std::string, std::vector<std::pair<FoodItem, float>>> meals;
    std::cout << "Enter nutrition plan name: ";
    std::getline(std::cin >> std::ws, name);
    if (nutritionPlanMap.find(name) != nutritionPlanMap.end())
    {
        if (!confirmOverwrite(nutritionPlanMap, name))
        {
            return;
        }
    }
    printWindowSizedSeparator();
    NutritionPlan plan(name, meals);
    modifyNutritionPlan(plan, foodItemMap);
    nutritionPlanMap[name] = plan;
    overwriteCSV(filename, nutritionPlanMap);
}
References ViewModel::confirmOverwrite(), filename, foodItemMap, modifyNutritionPlan(), nutritionPlanMap, overwriteCSV(), printWindowSizedSeparator(), and readFromCSV().
adjustNonProteinItems()
void NutritionPlanViewModel::adjustNonProteinItems (NutritionPlan & plan, float & currentCalories, float targetCalories, float & currentProtein, int maxIterations) private
Add non-protein items to match the caloric needs.
Adjust non-protein items in the plan to meet caloric needs.
Parameters
plan The nutrition plan.
currentCalories The current calories.
targetCalories The target calories.
currentProtein The current protein.
maxIterations The maximum number of iterations for adjustment.
plan The nutrition plan being modified.
currentCalories The current total calories in the plan.
targetCalories The target caloric value to adjust towards.
currentProtein The current total protein in the plan.
maxIterations The maximum number of iterations to attempt adjustments.
Definition at line 771 of file NutritionPlanViewModel.cpp.
{
    int iterationCount = 0;
    while (currentCalories < targetCalories && iterationCount < maxIterations)
    {
        bool caloriesMatched = false;
        for (auto& meal : plan.meals)
        {
            for (auto& foodPair : meal.second)
            {
                if (foodPair.first.categories.find("protein") == foodPair.first.categories.end())
                {
                    // Add non-protein items to meet caloric needs
                    float additionalQuantity = 10;  // Add 10g increments
                    float newPortion = foodPair.second + additionalQuantity;
                    currentCalories += foodPair.first.calories * additionalQuantity / 100;
                    currentProtein += foodPair.first.protein * additionalQuantity / 100;
                    foodPair.second = newPortion;
                    if (currentCalories >= targetCalories)
                    {
                        caloriesMatched = true;
                        break;
                    }
                }
            }
            if (caloriesMatched)
            {
                break;
            }
        }
        iterationCount++;
    }
}
References readFromCSV().
adjustPortions()
void NutritionPlanViewModel::adjustPortions (NutritionPlan & plan, float & currentCalories, float & currentProtein, float target, int maxIterations, bool isReducing) private
Adjust portions of the nutrition plan.
Adjust portions of food items in the plan based on target values.
Parameters
plan The nutrition plan.
currentCalories The current calories.
currentProtein The current protein.
target The target value for adjustment.
maxIterations The maximum number of iterations for adjustment.
isReducing Flag to indicate if the adjustment is for reducing or increasing.
plan The nutrition plan being modified.
currentCalories The current total calories in the plan.
currentProtein The current total protein in the plan.
target The target value to adjust towards (calories or protein).
maxIterations The maximum number of iterations to attempt adjustments.
isReducing True if reducing portions, false if increasing portions.
Definition at line 701 of file NutritionPlanViewModel.cpp.
{
    int iterationCount = 0;
    while ((isReducing ? currentCalories > target : currentCalories < target) && iterationCount < maxIterations)
    {
        float adjustmentFactor = target / currentCalories;
        for (auto& meal : plan.meals)
        {
            for (auto& foodPair : meal.second)
            {
                // Adjust the portion sizes based on the adjustment factor
                foodPair.second = std::max(0.0f, foodPair.second * adjustmentFactor);
            }
        }
        // Recalculate the current calories and protein after adjustment
        calculateCurrentValues(plan, currentCalories, currentProtein);
        iterationCount++;
    }
}
References calculateCurrentValues(), and readFromCSV().
adjustProtein()
void NutritionPlanViewModel::adjustProtein (NutritionPlan & plan, float & currentProtein, float targetProtein, float & currentCalories, int maxIterations, bool isIncreasing) private
Adjust the protein intake in the nutrition plan.
Adjust protein intake in the plan to meet target values.
Parameters
plan The nutrition plan.
currentProtein The current protein.
targetProtein The target protein.
currentCalories The current calories.
maxIterations The maximum number of iterations for adjustment.
isIncreasing Flag to indicate if the adjustment is for increasing or decreasing.
plan The nutrition plan being modified.
currentProtein The current total protein in the plan.
targetProtein The target protein value to adjust towards.
currentCalories The current total calories in the plan.
maxIterations The maximum number of iterations to attempt adjustments.
isIncreasing True if increasing protein intake, false if decreasing protein intake.
Definition at line 731 of file NutritionPlanViewModel.cpp.
{
    int iterationCount = 0;
    while ((isIncreasing ? currentProtein < targetProtein : currentProtein > targetProtein) && iterationCount < maxIterations)
    {
        for (auto& meal : plan.meals)
        {
            for (auto& foodPair : meal.second)
            {
                if (foodPair.first.protein > proteinPerHundredGrams)
                {
                    // Adjust the portion size for protein-rich food items
                    float adjustmentQuantity = isIncreasing ? 10.0f : -10.0f;  // Add or reduce 10g increments
                    float newPortion = std::max(0.0f, foodPair.second + adjustmentQuantity);
                    if (newPortion == 0.0f && !isIncreasing) continue; // Avoid underflow
                    currentCalories += foodPair.first.calories * adjustmentQuantity / 100;
                    currentProtein += foodPair.first.protein * adjustmentQuantity / 100;
                    foodPair.second = newPortion;
                    if ((isIncreasing ? currentProtein >= targetProtein : currentProtein <= targetProtein))
                    {
                        return;
                    }
                }
            }
        }
        iterationCount++;
    }
}
References proteinPerHundredGrams, and readFromCSV().
calculateCurrentValues()
void NutritionPlanViewModel::calculateCurrentValues (const NutritionPlan & plan, float & currentCalories, float & currentProtein) private
Calculate the current calories and protein in a plan.
Calculate current calories and protein in a plan.
Parameters
plan The nutrition plan.
currentCalories The calculated current calories.
currentProtein The calculated current protein.
plan The nutrition plan to calculate values for.
currentCalories The current total calories in the plan.
currentProtein The current total protein in the plan.
Definition at line 677 of file NutritionPlanViewModel.cpp.
{
    currentCalories = 0;
    currentProtein = 0;
    for (const auto& meal : plan.meals)
    {
        for (const auto& foodPair : meal.second)
        {
            // Calculate total calories and protein based on the portion sizes
            currentCalories += foodPair.first.calories * foodPair.second / 100;
            currentProtein += foodPair.first.protein * foodPair.second / 100;
        }
    }
}
References readFromCSV().
confirmAndRemovePlan()
void NutritionPlanViewModel::confirmAndRemovePlan (const std::string & selectedPlanName) private
Confirm and remove a selected nutrition plan.
Parameters
selectedPlanName The name of the selected nutrition plan.
selectedPlanName The name of the nutrition plan to remove.
Definition at line 578 of file NutritionPlanViewModel.cpp.
{
    const auto& plan = nutritionPlanMap[selectedPlanName];
    std::cout << "Selected nutrition plan:\n";
    displayPlan(plan);
    std::string confirm;
    do
    {
        std::cout << "Are you sure you want to delete the nutrition plan '" << selectedPlanName << "'? (yes/no): ";
        std::getline(std::cin >> std::ws, confirm);
    } while (confirm != "yes" && confirm != "no");
    if (confirm != "yes")
    {
        std::cout << "Nutrition plan not deleted.\n";
        return;
    }
    nutritionPlanMap.erase(selectedPlanName);
    overwriteCSV(filename, nutritionPlanMap);
    std::cout << "Nutrition plan '" << selectedPlanName << "' deleted.\n";
}
References displayPlan(), filename, nutritionPlanMap, overwriteCSV(), and readFromCSV().
displayCurrentFoods()
void NutritionPlanViewModel::displayCurrentFoods (const std::vector< std::pair< FoodItem, float > > & mealItems) private
Display current foods in a meal.
Parameters
mealItems The vector of food items and their quantities.
mealItems The list of food items in the meal.
Definition at line 198 of file NutritionPlanViewModel.cpp.
{
    for (size_t i = 0; i < mealItems.size(); ++i)
    {
        // Display each food item in the meal
        std::cout << i + 1 << ". " << mealItems[i].first.name << " (" << mealItems[i].second << "g)\n";
    }
}
References readFromCSV().
displayPlan()
void NutritionPlanViewModel::displayPlan (const NutritionPlan & plan) private
Display a nutrition plan.
Display a nutrition plan with all its meals and food items.
Parameters
plan The nutrition plan to display.
Definition at line 315 of file NutritionPlanViewModel.cpp.
{
    std::cout << "Name: " << plan.name << "\n";
    printWindowSizedSeparator();
    TotalNutrients totalPlan;
    for (const auto& mealName : MEAL_NAMES)
    {
        std::cout << mealName << ":\n";
        TotalNutrients totalMeal;
        for (const auto& foodPair : plan.meals.at(mealName))
        {
            const auto& foodItem = foodPair.first;
            float quantity = foodPair.second;
            // Print details of each food item
            printFoodItem(foodItem, quantity);
            // Calculate total nutrients for the meal
            totalMeal.calories += foodItem.calories * quantity / 100;
            totalMeal.protein += foodItem.protein * quantity / 100;
            totalMeal.carbs += foodItem.carbohydrates * quantity / 100;
            totalMeal.fats += foodItem.fats * quantity / 100;
        }
        // Print total nutrients for the meal
        printMealTotal(mealName, totalMeal);
        // Accumulate total nutrients for the entire plan
        totalPlan.calories += totalMeal.calories;
        totalPlan.protein += totalMeal.protein;
        totalPlan.carbs += totalMeal.carbs;
        totalPlan.fats += totalMeal.fats;
    }
    // Print total nutrients for the entire plan
    printPlanTotal(totalPlan);
}
References MEAL_NAMES, printFoodItem(), printMealTotal(), printPlanTotal(), printWindowSizedSeparator(), and readFromCSV().
finalAdjustment()
void NutritionPlanViewModel::finalAdjustment (NutritionPlan & plan, float & currentCalories, float targetCalories, float & currentProtein, float targetProtein) private
Perform final adjustments to ensure the values are within the goals.
Final adjustment to ensure the plan meets target values for calories and protein.
Parameters
plan The nutrition plan.
currentCalories The current calories.
targetCalories The target calories.
currentProtein The current protein.
targetProtein The target protein.
plan The nutrition plan being modified.
currentCalories The current total calories in the plan.
targetCalories The target caloric value to adjust towards.
currentProtein The current total protein in the plan.
targetProtein The target protein value to adjust towards.
Definition at line 815 of file NutritionPlanViewModel.cpp.
{
    const int maxIterations = 1000;
    int iterationCount = 0;
    // Final adjustment to reduce calories if they are too high
    if (currentCalories > targetCalories)
    {
        float reductionFactor = targetCalories / currentCalories;
        for (auto& meal : plan.meals)
        {
            for (auto& foodPair : meal.second)
            {
                float prevPortion = foodPair.second;
                // Reduce portion sizes proportionally
                foodPair.second = std::max(0.0f, foodPair.second * reductionFactor);
                currentCalories -= (prevPortion - foodPair.second) * foodPair.first.calories / 100;
            }
        }
    }
    // Final adjustment to reduce protein if it is too high
    adjustProtein(plan, currentProtein, targetProtein, currentCalories, maxIterations, false);
    // Final adjustment to add non-protein items if calories are too low
    while (currentCalories < targetCalories && iterationCount < maxIterations)
    {
        bool caloriesMatched = false;
        for (auto& meal : plan.meals)
        {
            for (auto& foodPair : meal.second)
            {
                if (foodPair.first.protein < proteinPerHundredGrams)
                {
                    // Add small increments of non-protein items
                    float additionalQuantity = 1;  // Add 1g increments
                    float newPortion = foodPair.second + additionalQuantity;
                    currentCalories += foodPair.first.calories * additionalQuantity / 100;
                    currentProtein += foodPair.first.protein * additionalQuantity / 100;
                    foodPair.second = newPortion;
                    if (currentCalories >= targetCalories)
                    {
                        caloriesMatched = true;
                        break;
                    }
                }
            }
            if (caloriesMatched)
            {
                break;
            }
        }
        iterationCount++;
    }
}
References adjustProtein(), proteinPerHundredGrams, and readFromCSV().
generateNextPlan()
NutritionPlan NutritionPlanViewModel::generateNextPlan (float targetCalories, float targetProtein) private
Generate the next nutrition plan based on the target calories and protein.
Generate the next nutrition plan in the shuffled order.
Parameters
targetCalories The target calories.
targetProtein The target protein.
Returns
The generated nutrition plan.
Parameters
targetCalories The target number of calories for the nutrition plan.
targetProtein The target amount of protein for the nutrition plan.
Returns
The generated nutrition plan.
Definition at line 625 of file NutritionPlanViewModel.cpp.
{
    if (nutritionPlanMap.empty())
    {
        throw std::runtime_error("No nutrition plans available");
    }
    // Shuffle the plan names if not already shuffled or all plans have been used
    if (shuffledPlanNames.empty() || currentPlanIndex >= shuffledPlanNames.size())
    {
        shufflePlanNames();
        currentPlanIndex = 0;
    }
    const int maxIterations = 1000;
    // Select the next plan in the shuffled order
    NutritionPlan selectedPlan = nutritionPlanMap.at(shuffledPlanNames[currentPlanIndex]);
    currentPlanIndex++;  // Move to the next plan
    NutritionPlan newPlan = selectedPlan;  // Start with a copy of the selected plan
    float currentCalories = 0;
    float currentProtein = 0;
    // Calculate the current calories and protein of the selected plan
    calculateCurrentValues(selectedPlan, currentCalories, currentProtein);
    // Reduce portions if the current calories are too high
    adjustPortions(newPlan, currentCalories, currentProtein, targetCalories, maxIterations, true);
    // Increase protein intake if it is below the target
    adjustProtein(newPlan, currentProtein, targetProtein, currentCalories, maxIterations, true);
    // Decrease protein intake if it is above the target
    adjustProtein(newPlan, currentProtein, targetProtein, currentCalories, maxIterations, false);
    // Add non-protein items to match caloric needs
    adjustNonProteinItems(newPlan, currentCalories, targetCalories, currentProtein, maxIterations);
    // Final adjustment to ensure the values are within the goals
    finalAdjustment(newPlan, currentCalories, targetCalories, currentProtein, targetProtein);
    return newPlan;
}
References adjustNonProteinItems(), adjustPortions(), adjustProtein(), calculateCurrentValues(), currentPlanIndex, finalAdjustment(), nutritionPlanMap, readFromCSV(), shuffledPlanNames, and shufflePlanNames().
getAvailableCategories()
std::vector< std::string > NutritionPlanViewModel::getAvailableCategories (const std::map< std::string, FoodItem > & foodItemMap) private
Get the available categories from the food item map.
Get available categories from the food item map.
Parameters
foodItemMap The map of food items.
Returns
A vector of available categories.
Parameters
foodItemMap The map of all food items.
Returns
A vector of available categories.
Definition at line 50 of file NutritionPlanViewModel.cpp.
{
    std::set<std::string> categories;
    for (const auto& pair : foodItemMap)
    {
        // Add all categories of each food item to the set
        categories.insert(pair.second.categories.begin(), pair.second.categories.end());
    }
    // Convert set to vector and return
    return std::vector<std::string>(categories.begin(), categories.end());
}
References foodItemMap, and readFromCSV().
handleAddFood()
void NutritionPlanViewModel::handleAddFood (NutritionPlan & selectedPlan, const std::map< std::string, FoodItem > & foodItemMap, const std::string & mealName) private
Handle the addition of a food item to a meal.
Handle adding food items to a meal in the nutrition plan.
Parameters
selectedPlan The selected nutrition plan.
foodItemMap The map of food items.
mealName The name of the meal.
selectedPlan The nutrition plan being modified.
foodItemMap The map of all food items.
mealName The name of the meal being modified.
Definition at line 68 of file NutritionPlanViewModel.cpp.
{
    // Get available categories
    auto categoryVec = getAvailableCategories(foodItemMap);
    // Display available categories
    for (size_t i = 0; i < categoryVec.size(); ++i)
    {
        std::cout << i + 1 << ". " << categoryVec[i] << "\n";
    }
    printWindowSizedSeparator();
    int categoryChoice;
    // Get user input for category selection
    getValidInput(categoryChoice, "Select a category by number: ", 1, static_cast<int>(categoryVec.size()));
    std::string category = categoryVec[categoryChoice - 1];
    std::vector<FoodItem> filteredFoodItems;
    while (true)
    {
        // Display food items in the selected category
        displayFoodItemsByCategory(foodItemMap, category, filteredFoodItems);
        int foodChoice;
        std::cout << "Select a food item by number (or '0' to go back): ";
        getValidInput(foodChoice, "Enter choice: ", 0, static_cast<int>(filteredFoodItems.size()));
        if (foodChoice == 0)
        {
            break;  // Exit the loop if the user chooses to go back
        }
        // Get the selected food item's name and quantity
        std::string foodName = filteredFoodItems[foodChoice - 1].name;
        float quantity;
        getValidInput(quantity, "Enter quantity in grams: ");
        // Add the food item to the selected meal in the nutrition plan
        selectedPlan.meals[mealName].emplace_back(foodItemMap.at(foodName), quantity);
        std::cout << "Food item added to " << mealName << ".\n";
        std::cout << "Press Enter to continue...\n";
        std::cin.get();
    }
}
References displayFoodItemsByCategory(), foodItemMap, getAvailableCategories(), getValidInput(), printWindowSizedSeparator(), and readFromCSV().
handleRemoveFood()
void NutritionPlanViewModel::handleRemoveFood (NutritionPlan & selectedPlan, const std::string & mealName) private
Handle the removal of a food item from a meal.
Handle removing food items from a meal in the nutrition plan.
Parameters
selectedPlan The selected nutrition plan.
mealName The name of the meal.
selectedPlan The nutrition plan being modified.
mealName The name of the meal being modified.
Definition at line 119 of file NutritionPlanViewModel.cpp.
{
    std::cout << "Current foods in " << mealName << ":\n";
    int index = 1;
    std::vector<std::string> foodNames;
    for (const auto& foodPair : selectedPlan.meals[mealName])
    {
        // Display current food items in the meal
        std::cout << index << ". " << foodPair.first.name << " (" << foodPair.second << "g)\n";
        foodNames.push_back(foodPair.first.name);
        index++;
    }
    int removeChoice;
    while (true)
    {
        // Get user input for the food item to remove
        getValidInput(removeChoice, "Enter the number of the food item to remove (or '0' to cancel): ", 0, static_cast<int>(foodNames.size()));
        if (removeChoice == 0)
        {
            std::cout << "Remove operation cancelled.\n";
            break;  // Exit the loop if the user chooses to cancel
        }
        // Remove the selected food item from the meal
        auto it = selectedPlan.meals[mealName].begin() + (removeChoice - 1);
        selectedPlan.meals[mealName].erase(it);
        std::cout << "Food item removed from " << mealName << ".\n";
        std::cout << "Press Enter to continue...\n";
        std::cin.get();
        break;
    }
    printWindowSizedSeparator();
}
References getValidInput(), printWindowSizedSeparator(), and readFromCSV().
importFromFile()
void NutritionPlanViewModel::importFromFile (const std::string & filename) override virtual
Import nutrition plans from a file.
Parameters
filename The name of the file to import nutrition plans from.
filename The filename from which to import nutrition plans.
Implements ViewModel.
Definition at line 501 of file NutritionPlanViewModel.cpp.
{
    auto items = readFromCSV<NutritionPlan, FoodItem>(filename, foodItemMap);
    for (const auto& item : items)
    {
        auto it = nutritionPlanMap.find(item.first);
        if (it != nutritionPlanMap.end())
        {
            clearScreen();
            const auto& currentPlan = it->second;
            const auto& newPlan = item.second;
            std::cout << "Nutrition plan '" << item.first << "' already exists.\n";
            std::cout << "Current plan:\n";
            displayPlan(currentPlan);
            std::cout << "New plan:\n";
            displayPlan(newPlan);
            if (confirmOverwrite(nutritionPlanMap, item.first))
            {
                nutritionPlanMap[item.first] = newPlan;
            }
        }
        else
        {
            nutritionPlanMap[item.first] = item.second;
        }
    }
    overwriteCSV("nutrition_plans.csv", nutritionPlanMap);
}
References clearScreen(), ViewModel::confirmOverwrite(), displayPlan(), filename, foodItemMap, nutritionPlanMap, overwriteCSV(), and readFromCSV().
modify()
void NutritionPlanViewModel::modify () override virtual
Modify an existing nutrition plan.
Implements ViewModel.
Definition at line 454 of file NutritionPlanViewModel.cpp.
{
    if (nutritionPlanMap.empty())
    {
        std::cout << "No nutrition plans available to modify.\n";
        return;
    }
    std::string selectedPlanName = selectPlan("modify");
    if (selectedPlanName.empty())
    {
        std::cout << "Modify operation cancelled.\n";
        return;
    }
    auto& selectedPlan = nutritionPlanMap[selectedPlanName];
    modifyNutritionPlan(selectedPlan, foodItemMap);
    overwriteCSV(filename, nutritionPlanMap);
}
References filename, foodItemMap, modifyNutritionPlan(), nutritionPlanMap, overwriteCSV(), readFromCSV(), and selectPlan().
modifyNutritionPlan()
void NutritionPlanViewModel::modifyNutritionPlan (NutritionPlan & selectedPlan, const std::map< std::string, FoodItem > & foodItemMap) private
Modify a nutrition plan.
Modify a nutrition plan by adding or removing food items.
Parameters
selectedPlan The nutrition plan to modify.
foodItemMap The map of food items.
selectedPlan The nutrition plan being modified.
foodItemMap The map of all food items.
Definition at line 158 of file NutritionPlanViewModel.cpp.
{
    std::string foodName;
    for (const auto& mealName : MEAL_NAMES)
    {
        while (true)
        {
            std::cout << "Current foods in " << mealName << ":\n";
            displayCurrentFoods(selectedPlan.meals[mealName]);
            std::cout << "Enter 'add' to add a new food, 'remove' to remove a food, 'done' to finish modifying " << mealName << ": ";
            std::getline(std::cin >> std::ws, foodName);
            printWindowSizedSeparator();
            if (foodName == "done")
            {
                break;  // Exit the loop if the user is done modifying
            }
            else if (foodName == "add")
            {
                handleAddFood(selectedPlan, foodItemMap, mealName);
            }
            else if (foodName == "remove")
            {
                handleRemoveFood(selectedPlan, mealName);
            }
            else
            {
                std::cout << "Invalid input.\n";
            }
        }
    }
}
References displayCurrentFoods(), foodItemMap, handleAddFood(), handleRemoveFood(), MEAL_NAMES, printWindowSizedSeparator(), and readFromCSV().
printFoodItem()
void NutritionPlanViewModel::printFoodItem (const FoodItem & foodItem, float quantity) private
Print a food item.
Print the details of a single food item.
Parameters
foodItem The food item to print.
quantity The quantity of the food item.
Definition at line 271 of file NutritionPlanViewModel.cpp.
{
    float calories = foodItem.calories * quantity / 100;
    float protein = foodItem.protein * quantity / 100;
    float carbs = foodItem.carbohydrates * quantity / 100;
    float fats = foodItem.fats * quantity / 100;
    // Display the details of the food item
    std::cout << std::fixed << std::setprecision(2);
    std::cout << "  " << foodItem.name << " - " << quantity << "g (Calories: " << calories
        << " kcal, Protein: " << protein << " g, Carbohydrates: " << carbs
        << " g, Fats: " << fats << " g, Portion: " << foodItem.portion << " g)\n";
}
References readFromCSV().
printMealTotal()
void NutritionPlanViewModel::printMealTotal (const std::string & mealName, TotalNutrients totalMeal) private
Print the total nutrients for a meal.
Print the total nutrients for a single meal.
Parameters
mealName The name of the meal.
totalMeal The total nutrients for the meal.
Definition at line 290 of file NutritionPlanViewModel.cpp.
{
    // Display the total nutrients for the meal
    std::cout << "  Total for " << mealName << ": " << totalMeal.calories << " kcal"
        << " (Protein: " << totalMeal.protein << " g, Carbohydrates: " << totalMeal.carbs
        << " g, Fats: " << totalMeal.fats << " g)\n";
}
References readFromCSV().
printPlanTotal()
void NutritionPlanViewModel::printPlanTotal (TotalNutrients totalPlan) private
Print the total nutrients for the entire plan.
Parameters
totalPlan The total nutrients for the entire plan.
totalPlan The total nutrients for the plan.
Definition at line 302 of file NutritionPlanViewModel.cpp.
{
    // Display the total nutrients for the plan
    std::cout << "Total for the plan: " << totalPlan.calories << " kcal"
        << " (Protein: " << totalPlan.protein << " g, Carbohydrates: " << totalPlan.carbs
        << " g, Fats: " << totalPlan.fats << " g)\n";
    printWindowSizedSeparator();
}
References printWindowSizedSeparator(), and readFromCSV().
reload()
void NutritionPlanViewModel::reload () override virtual
Reload the nutrition plans and food items from the CSV files.
Reload nutrition plans and food items from CSV files.
Implements ViewModel.
Definition at line 537 of file NutritionPlanViewModel.cpp.
{
    foodItemMap = readFromCSV<FoodItem>("food_items.csv");
    nutritionPlanMap = readFromCSV<NutritionPlan, FoodItem>(filename, foodItemMap);
}
References filename, foodItemMap, nutritionPlanMap, and readFromCSV().
remove()
void NutritionPlanViewModel::remove () override virtual
Remove a nutrition plan.
Remove an existing nutrition plan.
Implements ViewModel.
Definition at line 478 of file NutritionPlanViewModel.cpp.
{
    if (nutritionPlanMap.empty())
    {
        std::cout << "No nutrition plans available to delete.\n";
        return;
    }
    std::string selectedPlanName = selectPlan("delete");
    if (selectedPlanName.empty())
    {
        std::cout << "Delete operation cancelled.\n";
        return;
    }
    confirmAndRemovePlan(selectedPlanName);
}
References confirmAndRemovePlan(), nutritionPlanMap, readFromCSV(), and selectPlan().
selectPlan()
std::string NutritionPlanViewModel::selectPlan (const std::string & action) private
Select a nutrition plan for modification or deletion.
Parameters
action The action to be performed (modify/delete).
Returns
The name of the selected nutrition plan.
Parameters
action The action to perform on the selected plan ("modify" or "delete").
Returns
The name of the selected nutrition plan.
Definition at line 548 of file NutritionPlanViewModel.cpp.
{
    std::cout << "Select a nutrition plan to " << action << ":\n";
    int index = 1;
    std::vector<std::string> planNames;
    for (const auto& pair : nutritionPlanMap)
    {
        std::cout << index << ". " << pair.first << "\n";
        planNames.push_back(pair.first);
        ++index;
    }
    std::cout << index << ". Cancel\n";
    printWindowSizedSeparator();
    int choice;
    getValidInput(choice, "Enter choice: ", 1, index);
    if (choice == index)
    {
        return "";  // Return an empty string if the user chooses to cancel
    }
    return planNames[choice - 1];
}
References getValidInput(), nutritionPlanMap, printWindowSizedSeparator(), and readFromCSV().
shufflePlanNames()
void NutritionPlanViewModel::shufflePlanNames () private
Shuffle the plan names.
Shuffle the names of the nutrition plans.
Definition at line 606 of file NutritionPlanViewModel.cpp.
{
    shuffledPlanNames.clear();
    for (const auto& pair : nutritionPlanMap)
    {
        shuffledPlanNames.push_back(pair.first);
    }
    std::random_device rd;
    std::mt19937 g(rd());
    std::shuffle(shuffledPlanNames.begin(), shuffledPlanNames.end(), g);
}
References nutritionPlanMap, readFromCSV(), and shuffledPlanNames.
view()
void NutritionPlanViewModel::view () override virtual
Display the nutrition plans.
View nutrition plans based on user selection.
Implements ViewModel.
Definition at line 224 of file NutritionPlanViewModel.cpp.
{
    if (nutritionPlanMap.empty())
    {
        std::cout << "No nutrition plans available.\n";
        return;
    }
    int viewChoice;
    int optionsCount = viewOptions();
    getValidInput(viewChoice, "Enter choice: ", 1, optionsCount);
    printWindowSizedSeparator();
    switch (viewChoice)
    {
    case 1:
        viewAllPlans();
        break;
    case 2:
        viewPersonalizedPlan();
        break;
    case 3:
        std::cout << "View operation cancelled.\n";
        break;
    default:
        std::cout << "Invalid choice.\n";
        break;
    }
}
References getValidInput(), nutritionPlanMap, printWindowSizedSeparator(), readFromCSV(), viewAllPlans(), viewOptions(), and viewPersonalizedPlan().
viewAllPlans()
void NutritionPlanViewModel::viewAllPlans () private
View all nutrition plans.
Definition at line 258 of file NutritionPlanViewModel.cpp.
{
    for (const auto& pair : nutritionPlanMap)
    {
        displayPlan(pair.second);
    }
}
References displayPlan(), nutritionPlanMap, and readFromCSV().
viewPersonalizedPlan()
void NutritionPlanViewModel::viewPersonalizedPlan () private
View a personalized nutrition plan based on goals.
Definition at line 377 of file NutritionPlanViewModel.cpp.
{
    Goals goals;
    Profile profile;
    if (!tryLoadProfileAndGoals("profile.csv", "goals.csv", profile, goals)) return;
    goals.setProfile(&profile);
    float requiredCalories = goals.getDailyCalories();
    float requiredProtein = (goals.getFitnessGoal() == Goals::FitnessGoal::MUSCLE_GAIN) ?
        profile.getWeight() * 2.2f : profile.getWeight() * 1.6f;
    while (true)
    {
        NutritionPlan randomPlan = generateNextPlan(requiredCalories, requiredProtein);
        clearScreen();
        printLabel("Viewing generated nutrition plan");
        displayPlan(randomPlan);
        std::string choice;
        do
        {
            std::cout << "Do you want to generate another plan? (yes/no) or save (save): ";
            std::getline(std::cin >> std::ws, choice);
        } while (choice != "yes" && choice != "no" && choice != "save");
        if (choice == "no")
        {
            break;
        }
        else if (choice == "save")
        {
            std::string planName;
            std::cout << "Enter plan name: ";
            std::getline(std::cin >> std::ws, planName);
            randomPlan.name = planName;
            std::map<std::string, NutritionPlan> newPlan;
            newPlan[planName] = randomPlan;
            overwriteCSV("personal_nutritional_plan.csv", newPlan);
            std::cout << "Plan saved.\n";
            break;
        }
    }
}
References clearScreen(), displayPlan(), generateNextPlan(), Goals::getDailyCalories(), Goals::getFitnessGoal(), Profile::getWeight(), Goals::MUSCLE_GAIN, overwriteCSV(), printLabel(), readFromCSV(), Goals::setProfile(), and tryLoadProfileAndGoals().
Member Data Documentation
currentPlanIndex
size_t NutritionPlanViewModel::currentPlanIndex = 0 private
Current index of the nutrition plan.
Definition at line 71 of file NutritionPlanViewModel.h.
filename
std::string NutritionPlanViewModel::filename private
The name of the file containing the nutrition plans.
Definition at line 68 of file NutritionPlanViewModel.h.
foodItemMap
std::map<std::string, FoodItem> NutritionPlanViewModel::foodItemMap private
Map of food items.
Definition at line 70 of file NutritionPlanViewModel.h.
nutritionPlanMap
std::map<std::string, NutritionPlan> NutritionPlanViewModel::nutritionPlanMap private
Map of nutrition plans.
Definition at line 69 of file NutritionPlanViewModel.h.
proteinPerHundredGrams
const int NutritionPlanViewModel::proteinPerHundredGrams = 15 private
Protein amount per hundred grams.
Definition at line 73 of file NutritionPlanViewModel.h.
shuffledPlanNames
std::vector<std::string> NutritionPlanViewModel::shuffledPlanNames private
Vector of shuffled plan names.
Definition at line 72 of file NutritionPlanViewModel.h.
The documentation for this class was generated from the following files:
NutritionPlanViewModel.h
NutritionPlanViewModel.cpp