FitnessApp: ProfileView Class Reference
ProfileView Class Reference
The ProfileView class is responsible for managing the profile and goals settings. It inherits from the View class and provides options for viewing and modifying profile information and goals.
#include <ProfileView.h>
Public Member Functions
ProfileView (Profile &profile, Goals &goals)
Constructs a new ProfileView object.
void display ()
Displays the profile view menu.
Public Member Functions inherited from View
virtual ~View ()=default
Virtual destructor for the View class.
void displayAndHandleSubMenu (const std::string &title, const std::vector< MenuOption > &menuOptions, bool askForEnterAtTheEnd)
Displays a submenu and handles user input to navigate the options.
Private Member Functions
void setProfileInformation ()
Sets the profile information with optional inputs.
void setGoals ()
Sets the goals with optional inputs.
void setCustomCalories ()
Sets custom daily calories.
void resetToCalculatedCalories ()
Resets to calculated daily calories.
Goals::FitnessGoal getFitnessGoal (Goals::FitnessGoal currentGoal)
Prompts the user to select a fitness goal.
Profile::Gender getGender (Profile::Gender gender)
Prompts the user to select a gender.
Profile::ActivityLevel getActivityLevel (Profile::ActivityLevel currentActivityLevel)
Prompts the user to select an activity level.
Private Attributes
Profile & profile
Reference to the Profile object.
Goals & goals
Reference to the Goals object.
std::vector< MenuOption > menuOptions
Vector to store menu options.
Detailed Description
The ProfileView class is responsible for managing the profile and goals settings. It inherits from the View class and provides options for viewing and modifying profile information and goals.
Definition at line 12 of file ProfileView.h.
Constructor & Destructor Documentation
ProfileView()
ProfileView::ProfileView (Profile & profile, Goals & goals)
Constructs a new ProfileView object.
Parameters
profile Reference to the Profile object.
goals Reference to the Goals object.
Definition at line 79 of file ProfileView.cpp.
                                                       : profile(profile), goals(goals)
{
    menuOptions = {
        {"View Profile", [this]() { printLabel("Viewing Profile"); this->profile.displayProfileInformation(); this->goals.displayGoals(); }},
        {"Set Profile Information", [this]() { printLabel("Setting Profile Information"); setProfileInformation(); }},
        {"Set Goals", [this]() { printLabel("Setting Goals"); setGoals(); }},
        {"Set Custom Calories", [this]() { printLabel("Setting Custom Calories"); setCustomCalories(); }},
        {"Reset to Calculated Calories", [this]() { printLabel("Resetting to Calculated Calories"); resetToCalculatedCalories(); }},
        {"Back", [this]() { return; }}
    };
    // Load profile information from file
    if (profile.loadFromCSV("profile.csv"))
    {
        goals.setProfile(&profile);
    }
    // Load goals information from file
    goals.loadFromCSV("goals.csv");
}
References Goals::displayGoals(), Profile::displayProfileInformation(), goals, Goals::loadFromCSV(), Profile::loadFromCSV(), menuOptions, printLabel(), profile, resetToCalculatedCalories(), setCustomCalories(), setGoals(), Goals::setProfile(), and setProfileInformation().
Member Function Documentation
display()
void ProfileView::display () virtual
Displays the profile view menu.
Implements View.
Definition at line 103 of file ProfileView.cpp.
{
    displayAndHandleSubMenu("Profile", menuOptions, true);
}
References View::displayAndHandleSubMenu(), and menuOptions.
getActivityLevel()
Profile::ActivityLevel ProfileView::getActivityLevel (Profile::ActivityLevel currentActivityLevel) private
Prompts the user to select an activity level.
Parameters
currentActivityLevel The current activity level to display as default.
Returns
Profile::ActivityLevel The selected activity level or the current value if no input was given.
Definition at line 114 of file ProfileView.cpp.
{
    int activityChoice;
    std::string input;
    std::cout << "Select activity level:\n";
    std::cout << "1. Sedentary: little or no exercise\n";
    std::cout << "2. Lightly Active: exercise 1-3 times/week\n";
    std::cout << "3. Moderately Active: daily exercise or intense exercise 4-5 times/week\n";
    std::cout << "4. Very Active: intense exercise 6-7 times/week\n";
    std::cout << "5. Extra Active: physical job or daily intense exercise\n";
    std::cout << "Enter choice (" << profile.getActivityLevelString() << "): ";
    while (true)
    {
        std::getline(std::cin, input);
        if (input.empty())
        {
            return currentActivityLevel;
        }
        if (stringToInt(input, activityChoice) && activityChoice >= 1 && activityChoice <= 5)
        {
            switch (activityChoice)
            {
            case 1:
                return Profile::ActivityLevel::SEDENTARY;
            case 2:
                return Profile::ActivityLevel::LIGHTLY_ACTIVE;
            case 3:
                return Profile::ActivityLevel::MODERATELY_ACTIVE;
            case 4:
                return Profile::ActivityLevel::VERY_ACTIVE;
            case 5:
                return Profile::ActivityLevel::EXTRA_ACTIVE;
            default:
                std::cout << "Invalid choice, setting to Sedentary.\n";
                return Profile::ActivityLevel::SEDENTARY;
            }
        }
        else
        {
            std::cout << "Invalid input. Please enter a number between 1 and 5, or press Enter to keep current activity level: ";
        }
    }
}
References Profile::EXTRA_ACTIVE, Profile::getActivityLevelString(), Profile::LIGHTLY_ACTIVE, Profile::MODERATELY_ACTIVE, profile, readFromCSV(), Profile::SEDENTARY, stringToInt(), and Profile::VERY_ACTIVE.
getFitnessGoal()
Goals::FitnessGoal ProfileView::getFitnessGoal (Goals::FitnessGoal currentGoal) private
Prompts the user to select a fitness goal.
Parameters
currentGoal The current fitness goal to display as default.
Returns
Goals::FitnessGoal The selected fitness goal or the current value if no input was given.
Definition at line 239 of file ProfileView.cpp.
{
    int goalChoice;
    std::string input;
    std::cout << "Select fitness goal:\n";
    std::cout << "1. Weight Loss\n";
    std::cout << "2. Muscle Gain\n";
    std::cout << "3. Maintenance\n";
    std::cout << "Enter choice (" << goals.getFitnessGoalString() << "): ";
    while (true)
    {
        std::getline(std::cin, input);
        if (input.empty())
        {
            return currentGoal;
        }
        if (stringToInt(input, goalChoice) && goalChoice >= 1 && goalChoice <= 3)
        {
            switch (goalChoice)
            {
            case 1:
                return Goals::FitnessGoal::WEIGHT_LOSS;
            case 2:
                return Goals::FitnessGoal::MUSCLE_GAIN;
            case 3:
                return Goals::FitnessGoal::MAINTENANCE;
            default:
                std::cout << "Invalid choice, setting to Weight Loss.\n";
                return Goals::FitnessGoal::WEIGHT_LOSS;
            }
        }
        else
        {
            std::cout << "Invalid input. Please enter a number between 1 and 3, or press Enter to keep current goal: ";
        }
    }
}
References Goals::getFitnessGoalString(), goals, Goals::MAINTENANCE, Goals::MUSCLE_GAIN, readFromCSV(), stringToInt(), and Goals::WEIGHT_LOSS.
getGender()
Profile::Gender ProfileView::getGender (Profile::Gender gender) private
Prompts the user to select a gender.
Parameters
gender The current gender to display as default.
Returns
Profile::Gender The selected gender or the current value if no input was given.
Definition at line 167 of file ProfileView.cpp.
{
    std::string input;
    int genderChoice;
    std::cout << "Select gender (" << (gender == Profile::Gender::MALE ? "Male" : "Female") << "):\n";
    std::cout << "1. Male\n";
    std::cout << "2. Female\n";
    std::cout << "Enter choice (" << profile.getGenderString() << "): ";
    while (true)
    {
        std::getline(std::cin, input);
        if (input.empty())
        {
            break;
        }
        if (stringToInt(input, genderChoice) && (genderChoice == 1 || genderChoice == 2))
        {
            gender = (genderChoice == 1) ? Profile::Gender::MALE : Profile::Gender::FEMALE;
            break;
        }
        else
        {
            std::cout << "Invalid choice, please enter 1 or 2.\n";
        }
    }
    return gender;
}
References Profile::FEMALE, Profile::getGenderString(), Profile::MALE, profile, readFromCSV(), and stringToInt().
resetToCalculatedCalories()
void ProfileView::resetToCalculatedCalories () private
Resets to calculated daily calories.
Definition at line 308 of file ProfileView.cpp.
{
    goals.resetToCalculatedCalories();
    goals.saveToCSV("goals.csv");
}
References goals, Goals::resetToCalculatedCalories(), and Goals::saveToCSV().
setCustomCalories()
void ProfileView::setCustomCalories () private
Sets custom daily calories.
Definition at line 297 of file ProfileView.cpp.
{
    float customCalories;
    getValidInput(customCalories, "Enter custom daily calories: ");
    goals.setCustomCalories(customCalories);
    goals.saveToCSV("goals.csv");
}
References getValidInput(), goals, Goals::saveToCSV(), and Goals::setCustomCalories().
setGoals()
void ProfileView::setGoals () private
Sets the goals with optional inputs.
Definition at line 283 of file ProfileView.cpp.
{
    std::cout << "Enter new value (or press enter to keep current value)\n";
    float targetWeight = getOptionalFloatInput("Enter target weight (kg)", goals.getTargetWeight());
    float bodyFatPercentage = getOptionalFloatInput("Enter body fat percentage", goals.getBodyFatPercentage());
    Goals::FitnessGoal fitnessGoal = getFitnessGoal(goals.getFitnessGoal());
    goals.setGoals(targetWeight, bodyFatPercentage, fitnessGoal);
    goals.saveToCSV("goals.csv");
}
References Goals::getBodyFatPercentage(), Goals::getFitnessGoal(), getFitnessGoal(), getOptionalFloatInput(), Goals::getTargetWeight(), goals, Goals::saveToCSV(), and Goals::setGoals().
setProfileInformation()
void ProfileView::setProfileInformation () private
Sets the profile information with optional inputs.
Definition at line 201 of file ProfileView.cpp.
{
    std::cout << "Enter new value (or press enter to keep current value)\n";
    std::string name = getOptionalStringInput("Enter name", profile.getName());
    int age = getOptionalIntInput("Enter age", profile.getAge());
    Profile::Gender gender = getGender(profile.getGender());
    float height = getOptionalFloatInput("Enter height (cm)", profile.getHeight());
    float weight = getOptionalFloatInput("Enter weight (kg)", profile.getWeight());
    Profile::ActivityLevel activityLevel = getActivityLevel(profile.getActivityLevel());
    profile.setProfileInformation(name, age, gender, height, weight, activityLevel);
    profile.saveToCSV("profile.csv");
    goals.setProfile(&profile);
    goals.saveToCSV("goals.csv");
}
References Profile::getActivityLevel(), getActivityLevel(), Profile::getAge(), Profile::getGender(), getGender(), Profile::getHeight(), Profile::getName(), getOptionalFloatInput(), getOptionalIntInput(), getOptionalStringInput(), Profile::getWeight(), goals, profile, Goals::saveToCSV(), Profile::saveToCSV(), Goals::setProfile(), and Profile::setProfileInformation().
Member Data Documentation
goals
Goals& ProfileView::goals private
Reference to the Goals object.
Definition at line 30 of file ProfileView.h.
menuOptions
std::vector<MenuOption> ProfileView::menuOptions private
Vector to store menu options.
Definition at line 31 of file ProfileView.h.
profile
Profile& ProfileView::profile private
Reference to the Profile object.
Definition at line 29 of file ProfileView.h.
The documentation for this class was generated from the following files:
ProfileView.h
ProfileView.cpp