FitnessApp: WorkoutPlan Class Reference
WorkoutPlan Class Reference
Represents a workout plan consisting of a name, type, and weekly schedule of exercises.
#include <WorkoutPlan.h>
Classes
struct ExerciseDetails
Represents details of an exercise including name, sets, and reps.
Public Types
enum class PlanType {
STRENGTH , POWER , HYPERTROPHY , CONDITIONING ,
PUSH , PULL , LEGS
}
Enum representing different types of workout plans.
Public Member Functions
WorkoutPlan ()=default
Default constructor.
WorkoutPlan (const std::string &name, PlanType type, const std::map< std::string, std::vector< ExerciseDetails > > &weeklyPlan)
Constructs a new WorkoutPlan object.
void toCSV (std::ofstream &file) const
Writes the workout plan to a CSV file.
bool fromCSV (std::stringstream &ss)
Reads a workout plan from a CSV string stream.
Static Public Member Functions
static std::string planTypeToString (PlanType type)
Converts the PlanType enum to a string representation.
static PlanType stringToPlanType (const std::string &str)
Converts a string representation of a plan type to the corresponding PlanType enum.
Public Attributes
std::string name
The name of the workout plan.
PlanType type
The type of the workout plan.
std::map< std::string, std::vector< ExerciseDetails > > weeklyPlan
Key: Day of the week, Value: List of exercises.
Private Member Functions
void processExercises (const std::string &day, const std::string &dayExercises, std::map< std::string, std::vector< ExerciseDetails > > &weeklyPlan)
Processes exercises for a given day and adds them to the weekly plan.
Detailed Description
Represents a workout plan consisting of a name, type, and weekly schedule of exercises.
Definition at line 13 of file WorkoutPlan.h.
Member Enumeration Documentation
PlanType
enum class WorkoutPlan::PlanType strong
Enum representing different types of workout plans.
Enumerator
STRENGTH
Strength training.
POWER
Power training.
HYPERTROPHY
Hypertrophy training.
CONDITIONING
Conditioning training.
PUSH
Push workouts.
PULL
Pull workouts.
LEGS
Leg workouts.
Definition at line 20 of file WorkoutPlan.h.
    {
        STRENGTH,
        POWER,
        HYPERTROPHY,
        CONDITIONING,
        PUSH,
        PULL,
        LEGS,
        // Add more types as needed
    };
Constructor & Destructor Documentation
WorkoutPlan() [1/2]
WorkoutPlan::WorkoutPlan () default
Default constructor.
WorkoutPlan() [2/2]
WorkoutPlan::WorkoutPlan (const std::string & name, PlanType type, const std::map< std::string, std::vector< ExerciseDetails > > & weeklyPlan)
Constructs a new WorkoutPlan object.
Parameters
name The name of the workout plan
type The type of the workout plan
weeklyPlan A map containing the weekly plan with days as keys and a vector of ExerciseDetails as values
name The name of the workout plan.
type The type of the workout plan.
weeklyPlan A map containing the weekly plan with days as keys and a vector of ExerciseDetails as values.
Definition at line 12 of file WorkoutPlan.cpp.
    : name(name), type(type), weeklyPlan(weeklyPlan)
{
}
Member Function Documentation
fromCSV()
bool WorkoutPlan::fromCSV (std::stringstream & ss)
Reads a workout plan from a CSV string stream.
Parameters
ss The stringstream to read from
Returns
true if reading was successful, false otherwise
Parameters
ss The stringstream to read from.
Returns
true if reading was successful, false otherwise.
Definition at line 140 of file WorkoutPlan.cpp.
{
    std::string typeStr;
    if (std::getline(ss, name, ',') && std::getline(ss, typeStr, ','))
    {
        type = stringToPlanType(typeStr);
        weeklyPlan.clear();
        std::string dayExercises;
        for (const auto& day : DAYS_OF_WEEK)
        {
            if (std::getline(ss, dayExercises, ','))
            {
                processExercises(day, dayExercises, weeklyPlan);
            }
        }
        return true;
    }
    return false;
}
References DAYS_OF_WEEK, name, processExercises(), readFromCSV(), stringToPlanType(), type, and weeklyPlan.
planTypeToString()
std::string WorkoutPlan::planTypeToString (PlanType type) static
Converts the PlanType enum to a string representation.
Parameters
type The PlanType to convert
Returns
A string representation of the PlanType
Parameters
type The PlanType to convert.
Returns
A string representation of the PlanType.
Definition at line 23 of file WorkoutPlan.cpp.
{
    switch (type)
    {
    case PlanType::STRENGTH:
        return "Strength";
    case PlanType::POWER:
        return "Power";
    case PlanType::HYPERTROPHY:
        return "Hypertrophy";
    case PlanType::CONDITIONING:
        return "Conditioning";
    case PlanType::PUSH:
        return "Push";
    case PlanType::PULL:
        return "Pull";
    case PlanType::LEGS:
        return "Legs";
    default:
        return "Unknown";
    }
}
References CONDITIONING, HYPERTROPHY, LEGS, POWER, PULL, PUSH, STRENGTH, and type.
processExercises()
void WorkoutPlan::processExercises (const std::string & day, const std::string & dayExercises, std::map< std::string, std::vector< ExerciseDetails > > & weeklyPlan) private
Processes exercises for a given day and adds them to the weekly plan.
Parameters
day The day of the week
dayExercises The exercises for the day in string format
weeklyPlan The map to add the processed exercises to
day The day of the week.
dayExercises The exercises for the day in string format.
weeklyPlan The map to add the processed exercises to.
Definition at line 110 of file WorkoutPlan.cpp.
{
    std::vector<ExerciseDetails> exercises;
    if (dayExercises.empty() || dayExercises == " ")
    {
        weeklyPlan[day] = exercises;
        return;
    }
    std::stringstream ess(dayExercises);
    std::string exerciseDetails;
    while (std::getline(ess, exerciseDetails, ';'))
    {
        if (exerciseDetails.empty()) continue; // Skip empty entries
        ExerciseDetails details;
        std::string exerciseName = exerciseDetails.substr(0, exerciseDetails.find('='));
        std::string setsReps = exerciseDetails.substr(exerciseDetails.find('=') + 1);
        details.exerciseName = exerciseName;
        details.sets = std::stoi(setsReps.substr(0, setsReps.find('x')));
        details.reps = std::stoi(setsReps.substr(setsReps.find('x') + 1));
        exercises.push_back(details);
    }
    weeklyPlan[day] = exercises;
}
References WorkoutPlan::ExerciseDetails::exerciseName, readFromCSV(), and weeklyPlan.
stringToPlanType()
WorkoutPlan::PlanType WorkoutPlan::stringToPlanType (const std::string & str) static
Converts a string representation of a plan type to the corresponding PlanType enum.
Parameters
str The string representation of the plan type
Returns
The corresponding PlanType enum
Parameters
str The string representation of the plan type.
Returns
The corresponding PlanType enum.
Definition at line 52 of file WorkoutPlan.cpp.
{
    std::string strLower = toLower(str);
    if (strLower == "strength")
        return PlanType::STRENGTH;
    if (strLower == "power")
        return PlanType::POWER;
    if (strLower == "hypertrophy")
        return PlanType::HYPERTROPHY;
    if (strLower == "conditioning")
        return PlanType::CONDITIONING;
    if (strLower == "push")
        return PlanType::PUSH;
    if (strLower == "pull")
        return PlanType::PULL;
    if (strLower == "legs")
        return PlanType::LEGS;
    return PlanType::STRENGTH; // Default
}
References CONDITIONING, HYPERTROPHY, LEGS, POWER, PULL, PUSH, readFromCSV(), STRENGTH, and toLower().
toCSV()
void WorkoutPlan::toCSV (std::ofstream & file) const
Writes the workout plan to a CSV file.
Parameters
file The ofstream object to write to
file The ofstream object to write to.
Definition at line 78 of file WorkoutPlan.cpp.
{
    file << name << "," << planTypeToString(type) << ",";
    for (const auto& day : DAYS_OF_WEEK)
    {
        auto it = weeklyPlan.find(day);
        if (it != weeklyPlan.end())
        {
            for (size_t i = 0; i < it->second.size(); ++i)
            {
                const auto& exercise = it->second[i];
                file << exercise.exerciseName << "=" << exercise.sets << "x" << exercise.reps;
                if (i < it->second.size() - 1)
                {
                    file << ";";
                }
            }
            file << ",";
        }
    }
    file << "\n";
}
References DAYS_OF_WEEK, name, planTypeToString(), readFromCSV(), type, and weeklyPlan.
Member Data Documentation
name
std::string WorkoutPlan::name
The name of the workout plan.
Definition at line 74 of file WorkoutPlan.h.
type
PlanType WorkoutPlan::type
The type of the workout plan.
Definition at line 75 of file WorkoutPlan.h.
weeklyPlan
std::map<std::string, std::vector<ExerciseDetails> > WorkoutPlan::weeklyPlan
Key: Day of the week, Value: List of exercises.
Definition at line 76 of file WorkoutPlan.h.
The documentation for this class was generated from the following files:
WorkoutPlan.h
WorkoutPlan.cpp