FitnessApp: ExerciseView Class Reference
ExerciseView Class Reference
Handles the user interface for displaying and managing exercises.
#include <ExerciseView.h>
Public Member Functions
ExerciseView (ExerciseViewModel &viewModel)
Constructs an ExerciseView object.
void display ()
Displays the exercise menu and handles user interactions.
Public Member Functions inherited from View
virtual ~View ()=default
Virtual destructor for the View class.
void displayAndHandleSubMenu (const std::string &title, const std::vector< MenuOption > &menuOptions, bool askForEnterAtTheEnd)
Displays a submenu and handles user input to navigate the options.
Private Member Functions
void importFromFile ()
Imports exercises from a file.
Private Attributes
ExerciseViewModel & viewModel
Reference to the ExerciseViewModel object.
std::vector< MenuOption > menuOptions
List of menu options for the exercise view.
Detailed Description
Handles the user interface for displaying and managing exercises.
This class provides methods to display the exercise menu and handle user interactions.
Definition at line 15 of file ExerciseView.h.
Constructor & Destructor Documentation
ExerciseView()
ExerciseView::ExerciseView (ExerciseViewModel & vm)
Constructs an ExerciseView object.
Parameters
viewModel A reference to the ExerciseViewModel object.
Initializes the menu options for the exercise view.
Parameters
vm A reference to the ExerciseViewModel object.
Definition at line 10 of file ExerciseView.cpp.
                                                : viewModel(vm)
{
    menuOptions = {
        {"View Exercises", [this]() { printLabel("Viewing Exercises"); viewModel.view(); }},
        {"Add Exercise", [this]() { printLabel("Adding Exercise"); viewModel.add(); }},
        {"Modify Exercise", [this]() { printLabel("Modifying Exercise"); viewModel.modify(); }},
        {"Delete Exercise", [this]() { printLabel("Deleting Exercise"); viewModel.remove(); }},
        {"Import from file", [this]() { importFromFile(); }},
        {"Back", [this]() { return; }}
    };
}
References ExerciseViewModel::add(), importFromFile(), menuOptions, ExerciseViewModel::modify(), printLabel(), ExerciseViewModel::remove(), ExerciseViewModel::view(), and viewModel.
Member Function Documentation
display()
void ExerciseView::display () virtual
Displays the exercise menu and handles user interactions.
This method reloads the view model data and displays the exercise menu. It allows the user to select various actions related to exercises.
Implements View.
Definition at line 28 of file ExerciseView.cpp.
{
    viewModel.reload();
    displayAndHandleSubMenu("Exercises", menuOptions, true);
}
References View::displayAndHandleSubMenu(), menuOptions, ExerciseViewModel::reload(), and viewModel.
importFromFile()
void ExerciseView::importFromFile () private
Imports exercises from a file.
This method is used to import exercises from a specified file.
Prompts the user to enter a filename and imports exercises from the specified file.
Definition at line 39 of file ExerciseView.cpp.
{
    std::string filename;
    std::cout << "Enter the filename to import exercises from: ";
    std::getline(std::cin >> std::ws, filename);
    viewModel.importFromFile(filename);
    std::cout << "Exercises imported from file: " << filename << std::endl;
}
References ExerciseViewModel::importFromFile(), and viewModel.
Member Data Documentation
menuOptions
std::vector<MenuOption> ExerciseView::menuOptions private
List of menu options for the exercise view.
Definition at line 32 of file ExerciseView.h.
viewModel
ExerciseViewModel& ExerciseView::viewModel private
Reference to the ExerciseViewModel object.
Definition at line 31 of file ExerciseView.h.
The documentation for this class was generated from the following files:
ExerciseView.h
ExerciseView.cpp